import type { ArticleSeed } from '@/seed/types'

// Converted from the editorial batch by scripts/convert-articles.ts.
// Headings were detected heuristically from a PDF text export; review the
// structure in /admin before publishing.
const article: ArticleSeed = {
  slug: 'complete-local-seo-guide',
  title: 'The Complete Local SEO Guide',
  metaTitle: 'The Complete Local SEO Guide',
  metaDescription: 'Strategy, implementation, measurement, and procurement guidance for local and multi-location businesses A practical, EEAT-led resource for engineers, buyer…',
  excerpt: 'Strategy, implementation, measurement, and procurement guidance for local and multi-location businesses A practical, EEAT-led resource for engineers, buyers, procurement managers, marketing leaders, and technical decisio…',
  category: 'seo',
  publishedAt: '2026-08-22',
  author: 'digital-kingz',
  body: [
    { type: 'p', text: 'Strategy, implementation, measurement, and procurement guidance for local and multi-location businesses' },
    { type: 'p', text: 'A practical, EEAT-led resource for engineers, buyers, procurement managers, marketing leaders, and technical decision makers. Last reviewed: 11 September 2026.' },
    { type: 'h3', text: 'The Complete Local SEO Guide' },
    { type: 'p', text: 'Introduction Local SEO is the discipline of making a business easier to discover, evaluate, and contact when a prospective customer searches within a defined geographic market. It includes Google Search, Google Maps, local-pack visibility, branded searches, industry directories, location-specific organic results, reviews, structured data, and conversion measurement. For buyers, procurement managers, engineers, and technical decision makers, local SEO is not a collection of disconnected marketing tasks. It is a commercial operating system that connects accurate business data, credible local information, technical website performance, reviews, authority, and measurable buyer actions. A construction supplier in Lisbon may need to appear for searches such as “commercial concrete contractor Lisbon” and “industrial building materials supplier near me.” A multi-location healthcare provider needs each clinic to have accurate hours, services, booking links, reviews, and reliable location data. The goal is the same: reduce uncertainty for customers and search engines about who the business is, where it operates, what it offers, and how to take the next step. Key principle: Local SEO is not about manipulating Google Maps. It is about delivering accurate, useful, evidence-led information at the moment a buyer is researching, comparing, visiting, or ready to request a quote.' },
    { type: 'p', text: 'What is local SEO and why does it matter to buyers? How does local SEO differ from traditional SEO? Traditional SEO often targets broad product, service, or educational queries. Local search optimization focuses on matching a business to a user’s geographic need, location, and commercial context. It uses the same underlying SEO fundamentals, but adds location data, map visibility, reviews, citations, local pages, and operational accuracy. Area' },
    { type: 'h2', text: 'Traditional SEO' },
    { type: 'h3', text: 'Local SEO' },
    { type: 'h3', text: 'Typical query' },
    { type: 'h3', text: 'How does industrial HVAC work?' },
    { type: 'h3', text: 'Industrial HVAC contractor near me' },
    { type: 'h3', text: 'Primary need' },
    { type: 'h3', text: 'Research and education' },
    { type: 'p', text: 'Find, compare, call, visit, or request a quote' },
    { type: 'h2', text: 'Geographic relevance' },
    { type: 'h3', text: 'National or international' },
    { type: 'p', text: 'City, region, postcode, or proximity based' },
    { type: 'h2', text: 'Key assets' },
    { type: 'p', text: 'Guides, category pages, product pages' },
    { type: 'p', text: 'Business Profiles, location pages, reviews, citations' },
    { type: 'h2', text: 'Business outcome' },
    { type: 'h3', text: 'Traffic and broad lead generation' },
    { type: 'p', text: 'Calls, bookings, enquiries, visits, qualified local leads' },
    { type: 'p', text: 'Which business outcomes can local SEO improve?' },
    { type: 'ul', items: ['Qualified local enquiries, calls, appointments, and quote requests', 'Direction requests, showroom visits, store visits, and regional sales opportunities', 'Visibility for service-plus-location, supplier-plus-location, and “near me” searches', 'Buyer confidence through accurate contact information, reviews, case studies, and credentials'] },
    { type: 'ul', items: ['Lower reliance on paid media for recurring local non-brand demand'] },
    { type: 'p', text: 'What determines local visibility in Google Search and Maps? Google describes local results through relevance, distance, and prominence. Relevance is how closely business information matches the search; distance is the relationship between the business and the searcher or stated area; prominence reflects how established and well known a business appears. Teams can improve data quality, website usefulness, reviews, links, and local evidence, but cannot reliably manipulate proximity. Signal' },
    { type: 'h2', text: 'What it means' },
    { type: 'h3', text: 'Practical work' },
    { type: 'h3', text: 'Relevance' },
    { type: 'p', text: 'Does the business match the user’s need?' },
    { type: 'p', text: 'Accurate categories, services, complete profiles, strong service pages' },
    { type: 'h2', text: 'Distance' },
    { type: 'p', text: 'Is the business geographically appropriate?' },
    { type: 'h2', text: 'Honest location data and realistic service coverage' },
    { type: 'h3', text: 'Prominence' },
    { type: 'p', text: 'Does the business appear trusted and established?' },
    { type: 'p', text: 'Genuine reviews, local links, press, trade memberships, proof-led content' },
    { type: 'p', text: 'What are the most common local SEO mistakes?' },
    { type: 'ul', items: ['Creating near-identical city pages that add no local value', 'Using virtual offices, false addresses, or unstaffed locations', 'Adding keywords to a business name when they are not part of the real-world name', 'Publishing inconsistent names, addresses, phone numbers, hours, or categories', 'Buying reviews or selectively requesting feedback only from satisfied customers', 'Treating Google Business Profile as a one-time setup', 'Using schema that does not match visible, accurate page content', 'Reporting rankings without tracking calls, qualified leads, pipeline, or revenue'] },
    { type: 'p', text: 'How should a business create a local SEO strategy? How do you define local SEO goals and commercial KPIs? Start with the buyer action that creates value: a call, appointment, booking, request for proposal, form submission, product enquiry, or branch visit. Rankings are useful diagnostic metrics but should not be the final objective. Build a measurement model that connects data accuracy and visibility to conversion and revenue. Level' },
    { type: 'h2', text: 'Example measures' },
    { type: 'h3', text: 'Purpose' },
    { type: 'h3', text: 'Data quality' },
    { type: 'p', text: 'Profile completeness, listing accuracy, duplicate count' },
    { type: 'h2', text: 'Confirm a reliable foundation' },
    { type: 'h3', text: 'Visibility' },
    { type: 'p', text: 'Maps views, local-pack visibility, non-brand clicks' },
    { type: 'h2', text: 'Measure discoverability' },
    { type: 'h3', text: 'Conversion' },
    { type: 'p', text: 'Calls, bookings, quote forms, directions requests' },
    { type: 'h2', text: 'Measure buyer action' },
    { type: 'h3', text: 'Commercial value' },
    { type: 'p', text: 'Qualified leads, opportunity value, revenue, ROI' },
    { type: 'h2', text: 'Measure business impact' },
    { type: 'h3', text: 'The Complete Local SEO Guide' },
    { type: 'p', text: 'How do you perform local keyword research? Build keyword groups around actual services, locations, industries, buyer intent, urgency, and branded demand. Prioritize a phrase based on commercial value and serviceability, not search volume alone. A low-volume B2B query may represent a high-value contract.' },
    { type: 'ul', items: ['Service or product: “commercial roofing,” “industrial cleaning,” “local SEO services”', 'Location: “Lisbon,” “Cascais,” “Porto,” “Algarve,” and “near me”', 'Buyer intent: “supplier,” “contractor,” “company,” “quote,” “consultant,” and “services”', 'Industry: “construction,” “healthcare,” “retail,” “manufacturing,” and “hospitality”', 'Use case and urgency: “emergency repair,” “office fit-out,” “compliance inspection”', 'Brand queries: business name plus branch, city, service, or contact terms'] },
    { type: 'p', text: 'How do you map keywords to the right pages? Search need' },
    { type: 'h2', text: 'Best page type' },
    { type: 'h3', text: 'Example' },
    { type: 'h3', text: 'Understand a service' },
    { type: 'h3', text: 'Core service page' },
    { type: 'p', text: '/services/local-seo/' },
    { type: 'h2', text: 'Find an office or branch' },
    { type: 'h3', text: 'Location page' },
    { type: 'p', text: '/locations/lisbon/' },
    { type: 'h2', text: 'Find a service in a city' },
    { type: 'h3', text: 'Service-location page' },
    { type: 'p', text: '/local-seo/lisbon/' },
    { type: 'h2', text: 'Compare providers' },
    { type: 'h3', text: 'Commercial service page' },
    { type: 'p', text: '/local-seo-services/' },
    { type: 'h2', text: 'Evaluate scale' },
    { type: 'h3', text: 'Multi-location capability page' },
    { type: 'p', text: '/multi-location-seo/' },
    { type: 'h2', text: 'Verify expertise' },
    { type: 'h3', text: 'Case study' },
    { type: 'p', text: '/case-studies/local-seo/' },
    { type: 'p', text: 'How should multi-location companies prevent duplicate content? A template is useful, but a city page must contain meaningful information specific to that location. Include the local team, actual service availability, regional project examples, customer proof, location-specific operating details, imagery, directions, standards, and FAQs. Do not mass-publish pages that differ only by the city name. Example: Instead of “We provide industrial cleaning in Lisbon,” explain the local team’s service area, sectors served, shift coverage, site-access procedures, compliance documentation, and a permitted regional project example.' },
    { type: 'p', text: 'How do you build governance into local SEO? Assign an owner to every critical data field and process. Marketing may manage content, operations may control hours and addresses, engineering may deploy schema, customer service may handle reviews, and analytics may report revenue. Without named ownership, profile and location data degrade quickly. Asset' },
    { type: 'h2', text: 'Primary owner' },
    { type: 'h3', text: 'Review cycle' },
    { type: 'h3', text: 'Google Business Profile' },
    { type: 'h3', text: 'Local marketing or operations' },
    { type: 'h3', text: 'Monthly' },
    { type: 'h3', text: 'Address, hours, and service coverage' },
    { type: 'h3', text: 'Operations or location manager' },
    { type: 'h3', text: 'On every change' },
    { type: 'h3', text: 'Location pages' },
    { type: 'h3', text: 'Marketing with web and operations' },
    { type: 'h3', text: 'Quarterly' },
    { type: 'h3', text: 'Technical SEO and schema' },
    { type: 'h3', text: 'Engineering or web team' },
    { type: 'h3', text: 'Monthly and on release' },
    { type: 'h3', text: 'The Complete Local SEO Guide' },
    { type: 'h3', text: 'Asset' },
    { type: 'h3', text: 'Primary owner' },
    { type: 'h3', text: 'Review cycle' },
    { type: 'h3', text: 'Reviews' },
    { type: 'p', text: 'Customer experience and branch teams' },
    { type: 'h2', text: 'Weekly' },
    { type: 'h3', text: 'Reporting' },
    { type: 'h3', text: 'Analytics or marketing operations' },
    { type: 'h3', text: 'Monthly' },
    { type: 'p', text: 'How do you optimize a Google Business Profile? Google Business Profile is a core local SEO asset for visibility in Search and Maps. It should be managed as an official business record, with verified ownership, accurate information, approved workflows, and regular review.' },
    { type: 'p', text: 'Which Google Business Profile fields require governance?' },
    { type: 'ul', items: ['Business name and primary category', 'Address or service-area configuration', 'Phone number, website URL, and appointment or quote links', 'Opening hours, special hours, and holiday changes', 'Services, products, description, photos, and videos', 'Accessibility and operational attributes', 'Ownership, role-based access, questions, reviews, and message handling'] },
    { type: 'p', text: 'How should teams choose business categories? Choose the most specific accurate primary category for the actual main activity of the location. Add secondary categories only when they represent genuine, material services. Do not select categories merely because they have higher volume or competitors use them.' },
    { type: 'p', text: 'How should you write a Google Business Profile description? A useful description explains what the business does, who it serves, where it operates, what differentiates it, and how to contact it. Write naturally and avoid repetitive city names or unsupported “best” claims. Example: “ABC Build Group delivers commercial refurbishment, office fit-out, and maintenance services for property managers, retailers, and hospitality operators across Lisbon and Cascais. Our project team manages planning, site coordination, quality control, and handover documentation. Contact our Lisbon office to request a site assessment.”' },
    { type: 'p', text: 'How should businesses manage reviews without creating policy risk? Request genuine feedback consistently after a legitimate customer interaction. Use a direct review link or QR code, keep the request neutral, avoid incentives, respond professionally, and route recurring service issues back to operations. Reviews should strengthen customer experience, not become a superficial marketing exercise.' },
    { type: 'p', text: 'How should a business respond to negative reviews? Acknowledge the concern, avoid publishing private information, state that the issue will be investigated, and give the customer a practical route to continue the conversation. Do not argue publicly or copy the same response to every review.' },
    { type: 'p', text: 'How do service-area businesses handle local SEO correctly? Service-area businesses should use a genuine eligible operating location, hide the address when customers do not visit, define realistic service areas, and describe actual coverage on the website. Never create false offices or virtual The Complete Local SEO Guide' },
    { type: 'p', text: 'locations to target cities.' },
    { type: 'p', text: 'Which Google Business Profile mistakes should you avoid?' },
    { type: 'ul', items: ['Keyword-stuffed business names', 'Duplicate profiles for one location', 'Employee-home or virtual-office locations presented as branches', 'Incorrect opening hours and forgotten holiday updates', 'Unrelated categories and misleading service claims', 'Agency-only ownership of business assets', 'Bought, fake, or self-written reviews', 'Irrelevant landing pages and unmonitored customer questions'] },
    { type: 'p', text: 'Expert recommendation: Maintain two verified business-controlled owners for every critical profile. An agency can be a manager, but it should not be the only account holder.' },
    { type: 'p', text: 'How do you build a technically reliable local SEO foundation? How should location-page architecture be designed? Use a deliberate hierarchy: service pages, location hub, individual location pages, justified service-location pages, relevant industry pages, case studies, and conversion pages. Every page should have a unique purpose and should be connected with contextual internal links and breadcrumbs.' },
    { type: 'p', text: 'What should every high-quality location page include?' },
    { type: 'ul', items: ['Location-specific headline and value proposition', 'Accurate address or clearly explained service area', 'Phone, contact method, opening hours, and directions where appropriate', 'Services genuinely available from the location', 'Named experts, local staff, or technical contacts', 'Regional case studies, customer proof, and authentic imagery', 'Credentials, standards, certifications, or operational evidence', 'Location-specific FAQs and a clear call to action', 'Links to relevant service, industry, and nearby location pages'] },
    { type: 'p', text: 'How should you optimize title tags and headings? Use unique, descriptive titles that combine service, geography, and buyer relevance without repetition. For example, “Local SEO Services in Lisbon for Multi-Location Businesses” is clearer and more credible than “Best Local SEO Lisbon | Local SEO Lisbon Services | Local SEO Agency Lisbon.” Headings should answer real questions, such as “What does a local SEO audit include?”' },
    { type: 'p', text: 'Which technical SEO checks are essential? Area' },
    { type: 'h2', text: 'What to check' },
    { type: 'h3', text: 'Why it matters' },
    { type: 'h3', text: 'Indexability' },
    { type: 'p', text: 'Noindex tags, robots directives, sitemaps, canonicals' },
    { type: 'p', text: 'Important pages must be eligible to rank' },
    { type: 'h3', text: 'Area' },
    { type: 'h3', text: 'What to check' },
    { type: 'h3', text: 'Why it matters' },
    { type: 'h3', text: 'Crawlability' },
    { type: 'p', text: 'Broken links, errors, redirects, blocked resources' },
    { type: 'h2', text: 'Bots and users must reach key pages' },
    { type: 'h3', text: 'Page experience' },
    { type: 'h3', text: 'Mobile usability, speed, layout stability' },
    { type: 'h3', text: 'Local buyers often search on mobile' },
    { type: 'h3', text: 'Architecture' },
    { type: 'h3', text: 'Internal links, breadcrumbs, orphan pages' },
    { type: 'p', text: 'Supports discovery and understanding' },
    { type: 'h2', text: 'Duplicate control' },
    { type: 'h3', text: 'Duplicate URLs, parameters, similar pages' },
    { type: 'h3', text: 'Clarifies the preferred page' },
    { type: 'h3', text: 'Measurement' },
    { type: 'h3', text: 'Conversions, UTMs, CRM integration' },
    { type: 'p', text: 'Connects visibility to commercial value' },
    { type: 'p', text: 'How should LocalBusiness schema be implemented? Use JSON-LD and select the most specific valid LocalBusiness subtype that genuinely describes the organization or individual location. Keep every property aligned with visible page content and verified business data. Common fields include name, address, phone, URL, opening hours, geographic coordinates, images, and relevant same-as profiles. Google’s LocalBusiness documentation requires accurate, page-specific markup. It recommends validation through the Rich Results Test and confirms that eligibility does not guarantee a rich-result display.' },
    { type: 'p', text: 'How do you maintain NAP consistency and citations? NAP means Name, Address, and Phone number. Establish a central source of truth for every location, then use it to update Google, Bing, Apple Maps, relevant directories, industry associations, partners, and local platforms. Also control hours, URLs, categories, service areas, and contact details.' },
    { type: 'p', text: 'How do you earn local authority and links? Earn links through genuine local relationships and useful evidence. Good opportunities include trade bodies, certifications, supplier and manufacturer directories, chambers of commerce, regional business press, universities, events, community initiatives, and customer-approved case studies. Avoid low-quality, mass-produced directory links and paid link schemes.' },
    { type: 'p', text: 'How should businesses create content for Google Search and AI search? Create explicit, well-structured answers supported by identifiable evidence. Explain service scope, regional coverage, onboarding process, standards, named expertise, case studies, buyer requirements, and next steps. Use clear author and reviewer information. AI-assisted search benefits from consistent entity data, direct answers, accessible content, and trustworthy supporting material.' },
    { type: 'h2', text: 'What does EEAT look like in practice?' },
    { type: 'p', text: 'Element' },
    { type: 'h2', text: 'Evidence to publish' },
    { type: 'h3', text: 'Experience' },
    { type: 'h3', text: 'Original project photography, hands-on examples, operational details' },
    { type: 'h3', text: 'Expertise' },
    { type: 'h3', text: 'Named authors, technical reviewers, credentials, certifications' },
    { type: 'h3', text: 'Authoritativeness' },
    { type: 'h3', text: 'Trade memberships, quality publications, earned mentions, partnerships' },
    { type: 'h3', text: 'Trustworthiness' },
    { type: 'h3', text: 'Accurate contacts, transparent claims, editorial policy, updated pages' },
    { type: 'h3', text: 'The Complete Local SEO Guide' },
    { type: 'p', text: 'How do you measure, scale, and buy local SEO? Which local SEO metrics belong on an executive dashboard? KPI group' },
    { type: 'h2', text: 'Core metrics' },
    { type: 'h3', text: 'Decision supported' },
    { type: 'h3', text: 'Visibility' },
    { type: 'p', text: 'Maps views, local-pack visibility, non-brand clicks' },
    { type: 'h2', text: 'Where demand is being won or lost' },
    { type: 'h3', text: 'Profile health' },
    { type: 'h3', text: 'Completeness, accuracy, duplicate listings' },
    { type: 'h3', text: 'Operational readiness' },
    { type: 'h3', text: 'Reputation' },
    { type: 'p', text: 'Review volume, rating, recency, response time' },
    { type: 'h2', text: 'Trust and customer experience' },
    { type: 'h3', text: 'Website health' },
    { type: 'p', text: 'Indexed pages, crawl errors, speed, engagement' },
    { type: 'h2', text: 'Technical and content priorities' },
    { type: 'h3', text: 'Conversion' },
    { type: 'h3', text: 'Calls, forms, bookings, directions requests' },
    { type: 'h3', text: 'Buyer action' },
    { type: 'h3', text: 'Commercial value' },
    { type: 'h3', text: 'Qualified leads, pipeline, win rate, revenue' },
    { type: 'h3', text: 'Budget and supplier decisions' },
    { type: 'h3', text: 'How do you connect rankings to revenue?' },
    { type: 'p', text: 'Define conversion events, standardize UTM parameters, preserve reliable call tracking, and send source, location, service type, and landing-page data into the CRM. Review qualified leads, opportunity value, win rate, and revenue by location rather than relying on blended averages. A lower-traffic branch may be the strongest local SEO performer if it produces more valuable opportunities.' },
    { type: 'h2', text: 'How often should teams audit local SEO?' },
    { type: 'ul', items: ['Weekly: urgent review issues, customer questions, critical listing errors', 'Monthly: Profile accuracy, technical alerts, conversion data, and location performance', 'Quarterly: competitor review, citation health, content gaps, category relevance, and authority opportunities', 'Annually: location architecture, governance, tooling, budget, vendor performance, and strategic markets'] },
    { type: 'p', text: 'What is a practical 90-day local SEO implementation plan? Period' },
    { type: 'h2', text: 'Priority actions' },
    { type: 'h3', text: 'Deliverables' },
    { type: 'h3', text: 'Days 1–30' },
    { type: 'p', text: 'Audit profiles, listings, website, tracking, ownership, and duplicates' },
    { type: 'p', text: 'Audit, data inventory, issue backlog, KPI baseline' },
    { type: 'h2', text: 'Days 31–60' },
    { type: 'p', text: 'Optimize priority profiles and pages; correct citations; deploy schema; launch reviews' },
    { type: 'p', text: 'Updated assets, schema documentation, reporting dashboard' },
    { type: 'h2', text: 'Days 61–90' },
    { type: 'p', text: 'Build authority, publish local proof, improve conversion paths, review results' },
    { type: 'p', text: 'Content plan, outreach plan, performance review, next-quarter roadmap' },
    { type: 'h2', text: 'Should local SEO be managed in-house, through an agency, or with software?' },
    { type: 'h3', text: 'The Complete Local SEO Guide' },
    { type: 'h3', text: 'Model' },
    { type: 'h3', text: 'Best for' },
    { type: 'h3', text: 'Risk to manage' },
    { type: 'h3', text: 'In-house' },
    { type: 'p', text: 'Teams with marketing, web, and operations capability' },
    { type: 'h2', text: 'Capacity and specialist knowledge gaps' },
    { type: 'h3', text: 'Agency' },
    { type: 'p', text: 'Organizations needing strategy and broad execution' },
    { type: 'p', text: 'Ownership, transparency, and quality control' },
    { type: 'h2', text: 'Consultant' },
    { type: 'p', text: 'Audits, technical complexity, recovery, governance' },
    { type: 'p', text: 'Internal capacity to implement recommendations' },
    { type: 'h2', text: 'Software' },
    { type: 'h3', text: 'Large multi-location operations' },
    { type: 'h3', text: 'Assuming technology replaces strategy' },
    { type: 'h3', text: 'Hybrid' },
    { type: 'p', text: 'Enterprises needing internal ownership plus expertise' },
    { type: 'h2', text: 'Clear roles and no duplicated work' },
    { type: 'p', text: 'What should procurement teams ask a local SEO provider?' },
    { type: 'ul', items: ['How will you define success beyond rankings?', 'Who owns our Profiles, listings, content, analytics, and documentation?', 'Which tasks are included, automated, and performed by specialists?', 'How do you prevent fake reviews, inaccurate locations, or misleading schema?', 'How do you measure qualified leads, pipeline, and revenue?', 'What technical support and implementation documentation do you provide?', 'What access, data, assets, and content will remain with us if the engagement ends?', 'Can you show relevant, permissioned case studies and explain the methodology?'] },
    { type: 'h2', text: 'Summary' },
    { type: 'p', text: 'Successful local SEO begins with operational truth: accurate information, legitimate locations, useful pages, credible reviews, sound technical implementation, and clear ownership. Build a foundation that makes the organization easy for buyers and search engines to understand. Then measure visibility, conversions, qualified leads, and revenue by location. Sustainable local visibility is earned through reliable service delivery, evidence, and continuous maintenance—not shortcuts.' },
    { type: 'h2', text: 'Frequently asked questions' },
    { type: 'p', text: 'What is local SEO? Local SEO improves visibility for geographically relevant searches in Google Search, Google Maps, directories, and local organic results. It combines Profiles, location pages, reviews, citations, technical SEO, links, and measurement.' },
    { type: 'h2', text: 'How long does local SEO take?' },
    { type: 'p', text: 'Timelines depend on competition, data quality, existing authority, technical condition, reviews, and implementation speed. Critical corrections can help promptly; sustainable growth in prominence and non-brand visibility usually requires ongoing work over several months.' },
    { type: 'h2', text: 'Is Google Business Profile required?' },
    { type: 'p', text: 'It is not the only local SEO asset, but it is central to visibility in Google Maps and many local Search experiences. Verified, complete, accurate profiles are a priority.' },
    { type: 'h3', text: 'What are local citations?' },
    { type: 'p', text: 'Citations are online mentions of business identity data, including name, address, phone number, website, category, and hours. They appear on maps, directories, trade bodies, partner sites, and local platforms.' },
    { type: 'h2', text: 'What is LocalBusiness schema?' },
    { type: 'p', text: 'It is structured data that helps search engines understand factual business information. It must accurately reflect visible page content and the real-world business or location.' },
    { type: 'p', text: 'Can a service-area business rank outside its city? It can be relevant to markets it genuinely serves, but it should not create false locations. Visibility continues to depend on relevance, distance, prominence, and trustworthy business information.' },
    { type: 'h2', text: 'How do you measure local SEO ROI?' },
    { type: 'p', text: 'Track calls, bookings, forms, qualified leads, pipeline, revenue, and return on investment by location and source. Use UTM standards and CRM integration where possible.' },
    { type: 'p', text: 'Can you pay for higher organic local rankings? Paid advertising can create sponsored visibility, but it does not purchase better organic local rankings. Focus on accurate data, useful content, technical quality, reviews, and genuine prominence.' },
    { type: 'h2', text: 'Call to action' },
    { type: 'p', text: 'Request a Local SEO Readiness Assessment. Review your Google Business Profiles, location pages, technical SEO, LocalBusiness schema, citations, reviews, measurement, governance, and conversion opportunities. The outcome should be a prioritized 90-day roadmap built around qualified local demand rather than vanity metrics.' },
    { type: 'h2', text: 'Meta title' },
    { type: 'p', text: 'Local SEO Guide: Strategy, Implementation & ROI' },
    { type: 'h2', text: 'Meta description' },
    { type: 'p', text: 'Learn how to build a scalable local SEO strategy across Google Business Profile, Maps, location pages, reviews, citations, schema, technical SEO, and ROI reporting.' },
    { type: 'h2', text: 'Suggested schema markup' },
    { type: 'p', text: 'Use Article schema for this guide, BreadcrumbList for navigation, and only page-appropriate schema. For genuine business-location pages, use the most specific valid LocalBusiness subtype with accurate name, address, phone, URL, hours, and geographic data.' },
    { type: 'h2', text: 'Suggested internal links' },
    { type: 'ul', items: ['Local SEO services', 'Technical SEO audit', 'Google Business Profile optimization', 'Multi-location SEO strategy', 'LocalBusiness schema implementation', 'Local citation management', 'Online review management'] },
    { type: 'ul', items: ['Local SEO case studies', 'Request a local SEO readiness assessment'] },
    { type: 'h2', text: 'Suggested image ideas and alt tags' },
    { type: 'p', text: 'Image idea' },
    { type: 'h2', text: 'Suggested alt text' },
    { type: 'h3', text: 'Local SEO ecosystem diagram' },
    { type: 'p', text: 'Local SEO ecosystem connecting Google Business Profile, location pages, reviews, citations, schema, links, and analytics' },
    { type: 'h2', text: 'Local pack illustration' },
    { type: 'p', text: 'Google local search results showing relevance, distance, and prominence' },
    { type: 'h2', text: 'Location-page wireframe' },
    { type: 'p', text: 'Example location page with address, services, reviews, map, local case study, and quote form' },
    { type: 'h2', text: '90-day roadmap' },
    { type: 'p', text: 'Ninety-day local SEO implementation plan covering audit, optimization, authority, and reporting' },
    { type: 'h2', text: 'Executive dashboard' },
    { type: 'p', text: 'Local SEO dashboard with Maps visibility, reviews, calls, leads, and revenue by location' },
    { type: 'h2', text: 'References and editorial basis' },
    { type: 'p', text: 'This article is based on Google documentation covering local ranking guidance, LocalBusiness structured data, and helpful, reliable, people-first content. Verify operational and implementation details against current official documentation before deployment, particularly after platform, policy, CMS, or business-location changes. Official sources: Google Business Profile — Tips to improve your local ranking; Google Search Central — LocalBusiness structured data; Google Search Central — Creating helpful, reliable, people-first content.' },
  ],
  faqs: [
    { question: 'What does EEAT look like in practice?', answer: 'Element' },
    { question: 'How do you connect rankings to revenue?', answer: 'Define conversion events, standardize UTM parameters, preserve reliable call tracking, and send source, location, service type, and landing-page data into the CRM. Review qualified leads, opportunity value, win rate, and revenue by location rather than relying on blended averages. A lower-traffic branch may be the strongest local SEO performer if it produces more valuable opportunities.' },
    { question: 'How long does local SEO take?', answer: 'Timelines depend on competition, data quality, existing authority, technical condition, reviews, and implementation speed. Critical corrections can help promptly; sustainable growth in prominence and non-brand visibility usually requires ongoing work over several months.' },
    { question: 'Is Google Business Profile required?', answer: 'It is not the only local SEO asset, but it is central to visibility in Google Maps and many local Search experiences. Verified, complete, accurate profiles are a priority.' },
    { question: 'What are local citations?', answer: 'Citations are online mentions of business identity data, including name, address, phone number, website, category, and hours. They appear on maps, directories, trade bodies, partner sites, and local platforms.' },
    { question: 'What is LocalBusiness schema?', answer: 'It is structured data that helps search engines understand factual business information. It must accurately reflect visible page content and the real-world business or location.' },
  ],
  relatedServices: ['local-seo', 'seo'],
}

export default article
