import type { ArticleSeed } from '@/seed/types'

// Converted from the editorial batch by scripts/convert-articles.ts.
// Headings were detected heuristically from a PDF text export; review the
// structure in /admin before publishing.
const article: ArticleSeed = {
  slug: 'complete-lead-generation-guide',
  title: 'The Complete Lead Generation Guide',
  metaTitle: 'Complete Lead Generation Guide for B2B Growth',
  metaDescription: 'Learn how to build a B2B lead-generation system that attracts, qualifies, nurtures, and converts the right buyers into measurable sales opportunities.',
  excerpt: 'A practical B2B framework for attracting, qualifying, nurturing, and converting the right buyers into measurable sales opportunities.',
  category: 'growth',
  publishedAt: '2026-09-02',
  author: 'digital-kingz',
  body: [
    { type: 'p', text: 'A practical B2B framework for attracting, qualifying, nurturing, and converting the right buyers into measurable sales opportunities. Lead generation is the process of attracting potential buyers, helping them evaluate a solution, capturing their interest, and moving qualified prospects into a sales process. For B2B, technical, and high-value service businesses, effective lead generation is not about collecting the largest possible number of contacts—it is about creating measurable opportunities with companies that are likely to buy. This guide explains how to build a complete lead generation system that connects strategy, website conversion, content, paid campaigns, sales qualification, CRM workflows, and revenue reporting.' },
    { type: 'h2', text: '1. What Is Lead Generation?' },
    { type: 'p', text: 'What does lead generation mean in B2B marketing? Lead generation is the structured process of finding and converting people or organisations that may become customers. A lead is not automatically a customer, an opportunity, or even a good fit. It is an identifiable person or company that has shown some level of interest in your business. Interest may be expressed by visiting a high-intent service page, requesting a quote, booking a consultation, downloading a technical guide, registering for a webinar, calling your company, completing a project-enquiry form, asking for specifications, or responding to outreach.' },
    { type: 'ul', items: ['Attract the right people through search, ads, referrals, social media, email, and direct visits.', 'Clarify what you offer and who it is for within seconds.', 'Build trust by proving that your business can deliver the promised result.', 'Convert interest into a useful next step, such as a consultation, quote request, audit, demo, callback, or technical'] },
    { type: 'p', text: 'review.' },
    { type: 'ul', items: ['Route and nurture the lead so a genuine opportunity does not disappear after someone submits a form.'] },
    { type: 'p', text: 'A useful journey is: audience → interest → lead → qualified lead → opportunity → customer. The goal is not to push every website visitor directly into a sales call. Many prospects need information, evidence, comparison material, technical clarity, and internal approval before they are ready to speak with a supplier.' },
    { type: 'p', text: 'A business that receives fewer but better-qualified leads usually has a stronger lead-generation system than a business producing large volumes of low-value enquiries.' },
    { type: 'p', text: 'What is the difference between lead generation and demand generation? Area' },
    { type: 'h2', text: 'Demand generation' },
    { type: 'h3', text: 'Lead generation' },
    { type: 'h3', text: 'Primary purpose' },
    { type: 'h3', text: 'Create awareness, interest, and market demand' },
    { type: 'h3', text: 'Identify and capture people showing interest' },
    { type: 'h3', text: 'Main audience stage' },
    { type: 'h3', text: 'Early research or problem awareness' },
    { type: 'h3', text: 'Evaluation, consideration, or buying intent' },
    { type: 'h3', text: 'Typical content' },
    { type: 'p', text: 'Research, useful articles, thought leadership, video' },
    { type: 'h2', text: 'Landing pages, quote forms, guides, demos' },
    { type: 'h3', text: 'Key outcomes' },
    { type: 'h3', text: 'Reach, engagement, return visits' },
    { type: 'p', text: 'Enquiries, booked calls, MQLs, SQLs, opportunities' },
    { type: 'p', text: 'Demand generation helps prospects recognise that they have a problem worth solving. Lead generation gives those prospects a practical route to identify themselves and begin a conversation. The strongest B2B strategy uses both.' },
    { type: 'h2', text: 'What is the difference between a lead, MQL, SQL, and opportunity?' },
    { type: 'h3', text: 'The Complete Lead Generation Guide' },
    { type: 'h3', text: 'Stage' },
    { type: 'h3', text: 'Meaning' },
    { type: 'h3', text: 'Typical action' },
    { type: 'h3', text: 'Lead' },
    { type: 'h3', text: 'Known contact showing interest' },
    { type: 'h3', text: 'Record source, consent, engagement, and basic details' },
    { type: 'p', text: 'MQL' },
    { type: 'p', text: 'Marketing-qualified lead meeting agreed criteria' },
    { type: 'h2', text: 'Nurture or prepare for sales review' },
    { type: 'p', text: 'SAL' },
    { type: 'h2', text: 'Sales accepts that follow-up is justified' },
    { type: 'h3', text: 'Assign owner and begin contact' },
    { type: 'p', text: 'SQL' },
    { type: 'h2', text: 'Sales confirms need and potential' },
    { type: 'h3', text: 'Discovery, scoping, solution review' },
    { type: 'h3', text: 'Opportunity' },
    { type: 'h3', text: 'Realistic potential deal' },
    { type: 'h3', text: 'Forecast and progress through pipeline' },
    { type: 'h3', text: 'Customer' },
    { type: 'h3', text: 'Completed sale' },
    { type: 'h3', text: 'Onboard, deliver, retain, expand' },
    { type: 'p', text: 'Definitions should be agreed between marketing and sales. If marketing calls every download an MQL but sales considers only urgent, budgeted enquiries worthwhile, reporting will never align.' },
    { type: 'h2', text: 'Why does lead quality matter more than lead volume?' },
    { type: 'p', text: 'Low-quality leads consume time. Sales teams may spend hours responding to people outside the service area, businesses with no budget, students conducting research, or prospects not ready to act for years. A campaign with 45 leads, 20 qualified leads, and 10 opportunities can be much stronger than one with 200 leads and only two opportunities. Evaluate fit, need, authority, budget, timing, potential value, margin, and likely sales-cycle length.' },
    { type: 'h2', text: '2. Who Is the Right Buyer?' },
    { type: 'p', text: 'How do you define an ideal customer profile? An ideal customer profile, or ICP, describes the type of company most likely to receive value from your offer and become a profitable customer. It is not a vague target such as “small businesses” or “construction companies.” A useful ICP is specific enough to guide targeting, page messaging, sales qualification, and content planning.' },
    { type: 'ul', items: ['Industry or sector, company size, location, turnover, and purchasing capacity.', 'Project type, technical environment, and regulatory requirements.', 'Common operational challenges and buying triggers.', 'Typical contract size, sales-cycle length, and buying process.', 'Decision-making roles, supplier-selection criteria, and reasons prospects reject suppliers.'] },
    { type: 'p', text: 'For example, a commercial construction business may target property managers, developers, and facilities teams in Lisbon and Cascais that need renovation, fit-out, maintenance, or refurbishment services for commercial assets and require accountable project management.' },
    { type: 'h2', text: 'Who influences a B2B purchase decision?' },
    { type: 'p', text: 'Stakeholder' },
    { type: 'h2', text: 'Main concern' },
    { type: 'h3', text: 'Useful proof' },
    { type: 'h3', text: 'Economic buyer' },
    { type: 'h3', text: 'Cost, return, risk, impact' },
    { type: 'h3', text: 'ROI model, outcome, pricing logic' },
    { type: 'h3', text: 'Technical evaluator' },
    { type: 'h3', text: 'Specification, reliability, compatibility' },
    { type: 'h3', text: 'Technical documents, process, certification' },
    { type: 'h3', text: 'Procurement manager' },
    { type: 'h3', text: 'Supplier risk and terms' },
    { type: 'h3', text: 'Scope, evidence, credentials, delivery process' },
    { type: 'h3', text: 'Operations manager' },
    { type: 'h3', text: 'Practical outcome and disruption' },
    { type: 'h3', text: 'Timeline, workflow, support, onboarding' },
    { type: 'h3', text: 'Finance team' },
    { type: 'h3', text: 'Budget justification' },
    { type: 'h3', text: 'Cost breakdown and commercial assumptions' },
    { type: 'h3', text: 'End user' },
    { type: 'h3', text: 'Usability and adoption' },
    { type: 'h3', text: 'Demo, examples, implementation plan' },
    { type: 'p', text: 'A single generic sales page rarely persuades all stakeholders. The strongest websites help each buyer find relevant value and give internal champions material they can share with colleagues.' },
    { type: 'h3', text: 'How do you identify commercial intent?' },
    { type: 'p', text: 'High-intent searches often include supplier, company, service, agency, contractor, quote, cost, price, consultation, audit, demo, implementation, comparison, specification, procurement, and request proposal. Website behaviour also provides signals: repeat visits, case-study views, pricing-page visits, use of calculators, technical-document downloads, and consultation requests.' },
    { type: 'h2', text: 'How should you score and prioritise leads?' },
    { type: 'p', text: 'Lead scoring ranks prospects using fit, engagement, and buying readiness. A simple model can give points for target industry, relevant job role, repeat visits, pricing-page activity, or a consultation request; it can subtract points for being outside your service area or clearly outside the target market. Review the model with sales regularly. If highly scored leads rarely become opportunities, the scoring criteria or ICP needs adjustment.' },
    { type: 'h2', text: '3. Which Channels Generate Qualified Leads?' },
    { type: 'p', text: 'How can SEO generate qualified leads? Search engine optimisation can create long-term demand by making useful pages visible when buyers search for information, solutions, suppliers, costs, specifications, comparisons, or implementation support. SEO works best when content serves distinct levels of intent. Content type' },
    { type: 'h2', text: 'Search intent' },
    { type: 'h3', text: 'Lead-generation role' },
    { type: 'h3', text: 'Educational guide' },
    { type: 'h3', text: 'Research' },
    { type: 'h3', text: 'Build trust and capture early interest' },
    { type: 'h3', text: 'Service page' },
    { type: 'h3', text: 'Solution or supplier search' },
    { type: 'h3', text: 'Generate direct enquiries' },
    { type: 'h3', text: 'Industry page' },
    { type: 'h3', text: 'Sector-specific evaluation' },
    { type: 'h3', text: 'Demonstrate relevance' },
    { type: 'h3', text: 'Case study' },
    { type: 'h3', text: 'Proof and risk reduction' },
    { type: 'h3', text: 'Support supplier selection' },
    { type: 'h3', text: 'Comparison page' },
    { type: 'h3', text: 'Commercial investigation' },
    { type: 'h3', text: 'Help buyers evaluate alternatives' },
    { type: 'h3', text: 'Cost guide' },
    { type: 'h3', text: 'Budget planning' },
    { type: 'h3', text: 'Attract high-intent buyers' },
    { type: 'p', text: 'Create content around real commercial and technical decisions. Use original expertise, specific examples, clear authorship, verifiable evidence, and links to relevant service, proof, and contact pages. Google’s guidance for Search and AI features emphasises helpful, reliable, people-first information, accessible text, clear internal linking, and content that provides original value. [web:17][web:21]' },
    { type: 'h2', text: 'When should you use paid search and paid social?' },
    { type: 'p', text: 'Paid search is valuable when people already have clear intent, such as searches for a supplier, audit, quote, or service. Paid social is useful when you need to reach defined roles, industries, company sizes, or target accounts before they actively search. Match the promise in the ad, email, or social post to the headline and CTA on the landing page.' },
    { type: 'h2', text: 'How does content marketing support lead generation?' },
    { type: 'p', text: 'Content marketing should help buyers make better decisions, not simply fill a publishing calendar. Useful formats include definitive guides, technical explainers, implementation checklists, procurement checklists, comparison guides, case studies, calculators, templates, webinars, and FAQs. Use content to explain trade-offs, address objections, demonstrate your process, and support sales follow-up.' },
    { type: 'h2', text: 'How can email marketing nurture potential buyers?' },
    { type: 'p', text: 'Most B2B buyers do not convert after one visit. Segment email activity by industry, role, service interest, company size, location, funnel stage, and engagement. A good sequence provides the next useful answer: deliver the requested resource, explain a common challenge, share a case study, address an objection, then offer a relevant consultation or audit.' },
    { type: 'h3', text: 'When does account-based marketing make sense?' },
    { type: 'p', text: 'Account-based marketing is useful when a small number of target accounts could create significant revenue. It is suited to high-value contracts, long sales cycles, complex buying committees, and defined markets. Build it around relevant research, role-specific messaging, tailored pages, credible proof, and human-led outreach—not generic mass messaging.' },
    { type: 'h2', text: '4. How Do You Convert and Manage Leads?' },
    { type: 'p', text: 'What should a high-converting landing page include? A landing page should have one primary purpose, such as generating a quote request, booking a consultation, registering a demo, downloading a guide, or requesting an audit.' },
    { type: 'ul', items: ['An outcome-led headline and a defined audience.', 'A concise explanation of the offer and buyer problem.', 'Relevant benefits and a simple process explanation.', 'Trust signals: case studies, testimonials, credentials, or results.', 'One primary call to action, a usable form or booking tool, and privacy reassurance.', 'FAQ content that addresses realistic objections.', 'Fast, stable mobile experience.'] },
    { type: 'p', text: 'Example: “Get a B2B Website Lead Generation Audit. Find out where your website is losing qualified prospects and receive practical recommendations for messaging, conversion paths, forms, tracking, and sales follow-up.”' },
    { type: 'h2', text: 'Which calls to action work at each buyer stage?' },
    { type: 'p', text: 'Buyer stage' },
    { type: 'h2', text: 'Best CTA types' },
    { type: 'h3', text: 'Example' },
    { type: 'h3', text: 'Early research' },
    { type: 'h3', text: 'Guide, checklist, calculator, webinar' },
    { type: 'h3', text: 'Download the Lead Qualification Checklist' },
    { type: 'h3', text: 'Active evaluation' },
    { type: 'h3', text: 'Case study, audit, consultation, demo' },
    { type: 'h3', text: 'Request a Website Lead Generation Audit' },
    { type: 'h3', text: 'Decision stage' },
    { type: 'h3', text: 'Quote, proposal, call, site visit' },
    { type: 'h3', text: 'Request a Project Estimate' },
    { type: 'h3', text: 'Existing customer' },
    { type: 'h3', text: 'Training, review, expansion call' },
    { type: 'h3', text: 'Book a Quarterly Growth Review' },
    { type: 'p', text: 'A clear CTA states what the visitor receives, what effort is required, and what happens next. “Request Your Lead Generation Review” is more useful than “Submit.”' },
    { type: 'h2', text: 'How much information should a lead form collect?' },
    { type: 'p', text: 'The purpose of the form determines the right length. A newsletter may need only an email address. A consultation or quote request may require name, company, work email, phone, role, service required, project details, budget range, desired timeline, and location. Request only information that improves the next conversation. Test the balance between conversion friction and qualification quality.' },
    { type: 'h2', text: 'How can trust signals improve conversion?' },
    { type: 'p', text: 'Trust signals reduce the perceived risk of contacting or choosing a supplier. Use named testimonials, relevant client logos, detailed case studies, portfolio examples, certifications, security or compliance information, named experts, transparent processes, response expectations, and verifiable company details. Specific evidence is more persuasive than unsubstantiated phrases such as “industry-leading.”' },
    { type: 'h2', text: 'What happens after a prospect submits a form?' },
    { type: 'p', text: 'The post-form experience is part of lead generation. Confirm receipt immediately, explain what happens next, provide a realistic response window, create or update the CRM record, attribute the source, route the lead to the' },
    { type: 'p', text: 'correct owner, notify that owner, begin follow-up, and record the outcome.' },
    { type: 'h2', text: 'How do you create an effective lead-nurturing process?' },
    { type: 'p', text: 'Nurture prospects who are relevant but not ready to buy. The sequence should be timely, segmented, helpful, and connected to sales signals. For example: deliver the guide immediately; after several days explain a common challenge; then share a relevant case study; later offer an assessment, consultation, or technical review.' },
    { type: 'h2', text: 'How do you prevent good leads from being lost?' },
    { type: 'p', text: 'Create a service-level agreement between marketing and sales. Define ownership, response-time standards, qualification rules, CRM stages, disqualification reasons, follow-up reminders, and escalation. A high-intent enquiry should never sit unassigned in an inbox.' },
    { type: 'h2', text: 'How do you help technical and procurement buyers move forward?' },
    { type: 'p', text: 'Make specifications, service scope, implementation process, compatibility, security, compliance, certifications, delivery timelines, support model, pricing principles, and risk-management information easy to find. Serious buyers need material they can evaluate and share internally.' },
    { type: 'h2', text: '5. How Do You Measure and Improve Lead Generation?' },
    { type: 'p', text: 'Which lead-generation metrics matter? Metric' },
    { type: 'h2', text: 'What it shows' },
    { type: 'h3', text: 'Relevant traffic' },
    { type: 'h3', text: 'Whether the right audience is arriving' },
    { type: 'h3', text: 'Landing-page conversion rate' },
    { type: 'h3', text: 'How effectively a page creates action' },
    { type: 'h3', text: 'Cost per lead' },
    { type: 'h3', text: 'Campaign efficiency at lead level' },
    { type: 'h3', text: 'Cost per qualified lead' },
    { type: 'h3', text: 'Efficiency after quality filtering' },
    { type: 'h3', text: 'MQL and SQL volume' },
    { type: 'h3', text: 'Marketing-generated sales potential' },
    { type: 'h3', text: 'Opportunity rate' },
    { type: 'h3', text: 'How often leads become deals' },
    { type: 'h3', text: 'Pipeline value' },
    { type: 'h3', text: 'Potential revenue from opportunities' },
    { type: 'h3', text: 'Lead-to-customer rate' },
    { type: 'h3', text: 'Overall quality and sales effectiveness' },
    { type: 'h3', text: 'Revenue sourced' },
    { type: 'h3', text: 'Direct commercial outcome' },
    { type: 'h3', text: 'How do you track lead quality instead of only lead quantity?' },
    { type: 'p', text: 'For each lead, record source, campaign, landing page, buyer role, company size, industry, score, qualification status, disqualification reason, opportunity value, sales-cycle duration, closed revenue, and lifetime value where available. This lets you identify whether a problem is caused by traffic quality, the offer, the landing page, qualification, sales follow-up, or the wider commercial process.' },
    { type: 'h2', text: 'How do you calculate lead-generation ROI?' },
    { type: 'p', text: 'A basic calculation is: Lead Generation ROI = (Revenue attributable to lead generation − total investment) / total investment × 100. Include paid media, content production, technology, landing-page work, and relevant sales costs. In long B2B sales cycles, pipeline value and opportunity quality may be useful leading indicators before revenue is fully realised.' },
    { type: 'h2', text: 'How should you test and improve performance?' },
    { type: 'p', text: 'Use a disciplined process: identify a problem, form a hypothesis, choose one meaningful change, launch the test, measure conversion and lead-quality results, record the learning, then keep, improve, or reverse the change.' },
    { type: 'p', text: 'Prioritise value proposition, offer, CTA, proof, form design, mobile usability, speed, and follow-up timing over minor visual changes.' },
    { type: 'h2', text: 'What are the most common lead-generation mistakes?' },
    { type: 'ul', items: ['Targeting everyone rather than a defined ICP.', 'Optimising for cheap leads instead of commercial fit.', 'Sending all traffic to a generic homepage.', 'Using vague messaging and unsupported claims.', 'Hiding technical, process, pricing, or proof information buyers need.', 'Using forms that are too long or too unqualified.', 'Treating marketing and sales as disconnected systems.', 'Ignoring mobile conversion and response time.', 'Reporting only traffic and lead counts, rather than pipeline and revenue.', 'Publishing thin, repetitive, or unreviewed AI-generated content.'] },
    { type: 'p', text: 'Google’s current AI and Search guidance does not require artificial AI-only formatting or special schema. Apply established SEO fundamentals: make essential information available in text, build useful internal links, provide a sound page experience, and publish original, trustworthy information. [web:17][web:21]' },
    { type: 'h2', text: 'What is a practical 90-day plan?' },
    { type: 'p', text: 'Days 1–30: define the ICP and lead stages; audit recent leads, pages, forms, CTAs, analytics, and CRM ownership; repair the biggest conversion leaks. Days 31–60: improve priority service pages; create focused landing pages; add proof; implement routing and tracking; launch a nurture sequence; publish one high-value asset. Days 61–90: review lead quality and pipeline data; improve the most important page; test one offer, CTA, or form change; expand the channels and content producing qualified opportunities.' },
    { type: 'h2', text: 'Summary' },
    { type: 'p', text: 'A complete lead-generation system is built around commercial relevance. Define the right buyer, create useful content and offers, build trust, provide clear conversion paths, qualify intelligently, follow up quickly, track outcomes in the CRM, and continuously improve based on pipeline and revenue data. When these elements work together, your website and marketing become a reliable source of qualified sales opportunities.' },
    { type: 'h2', text: 'Frequently Asked Questions' },
    { type: 'p', text: 'What is lead generation in B2B marketing? It is the process of attracting and identifying potential business customers, then moving suitable prospects toward a sales conversation through content, campaigns, website conversion, qualification, and follow-up. How can a website generate leads? A website generates leads by attracting relevant traffic, clearly explaining the offer, proving credibility, providing a useful CTA, using a suitable form or booking tool, and routing the enquiry into a timely follow-up process. Why am I getting leads but not sales? The problem may be targeting, qualification, offer quality, landing-page messaging, lack of trust, pricing, technical fit, sales follow-up, or a poorly defined sales process. Track disqualification reasons and pipeline progression to diagnose it. Can AI-generated content support lead generation? Yes, if it is accurate, reviewed, useful, original, and grounded in genuine expertise. AI content should not replace subject-matter review, evidence, quality control, or transparent authorship. [web:20]' },
  ],
  faqs: [
    { question: '1. What Is Lead Generation?', answer: 'What does lead generation mean in B2B marketing? Lead generation is the structured process of finding and converting people or organisations that may become customers. A lead is not automatically a customer, an opportunity, or even a good fit. It is an identifiable person or company that has shown some level of interest in your business. Interest may be expressed by visiting a high-intent service page, requesting a quote, booking a consultation, downloading a technical guide, registering for a webinar, calling your company, completing a project-enquiry form, asking for specifications, or respo' },
    { question: 'Why does lead quality matter more than lead volume?', answer: 'Low-quality leads consume time. Sales teams may spend hours responding to people outside the service area, businesses with no budget, students conducting research, or prospects not ready to act for years. A campaign with 45 leads, 20 qualified leads, and 10 opportunities can be much stronger than one with 200 leads and only two opportunities. Evaluate fit, need, authority, budget, timing, potential value, margin, and likely sales-cycle length.' },
    { question: '2. Who Is the Right Buyer?', answer: 'How do you define an ideal customer profile? An ideal customer profile, or ICP, describes the type of company most likely to receive value from your offer and become a profitable customer. It is not a vague target such as “small businesses” or “construction companies.” A useful ICP is specific enough to guide targeting, page messaging, sales qualification, and content planning.' },
    { question: 'Who influences a B2B purchase decision?', answer: 'Stakeholder' },
    { question: 'How do you identify commercial intent?', answer: 'High-intent searches often include supplier, company, service, agency, contractor, quote, cost, price, consultation, audit, demo, implementation, comparison, specification, procurement, and request proposal. Website behaviour also provides signals: repeat visits, case-study views, pricing-page visits, use of calculators, technical-document downloads, and consultation requests.' },
    { question: 'How should you score and prioritise leads?', answer: 'Lead scoring ranks prospects using fit, engagement, and buying readiness. A simple model can give points for target industry, relevant job role, repeat visits, pricing-page activity, or a consultation request; it can subtract points for being outside your service area or clearly outside the target market. Review the model with sales regularly. If highly scored leads rarely become opportunities, the scoring criteria or ICP needs adjustment.' },
  ],
  relatedServices: ['conversion-optimization', 'crm-systems'],
}

export default article
