import type { ServiceSeed } from '@/seed/types'

const service: ServiceSeed = {
  slug: 'local-seo',
  category: 'get-found',
  title: 'Local SEO',
  navLabel: 'Local SEO',
  tagline: 'Map pack visibility built on profile completeness, citations, reviews and local content.',
  icon: 'MapPin',
  metaTitle: 'Local SEO and Map Pack Visibility | Digital Kingz',
  metaDescription:
    'Local SEO built around how the map pack actually ranks: Google Business Profile optimization, relevance, prominence, citation accuracy and review velocity.',
  heroEyebrow: 'Grow / Local SEO',
  heroHeading: 'The Map Pack Is the Shortest Path to a Phone Call',
  heroSubheading:
    'Google Business Profile optimization, citation and review infrastructure, and location content built around the signals that actually decide who appears in local results.',
  intro: [
    'Local search compresses the buying journey more than any other channel. Someone searching for a service nearby is usually past research and into selection, and the results they see carry a phone number, directions, opening hours and reviews before they have visited a website at all. The distance between impression and enquiry is one tap, which is why local visibility converts at a rate the rest of search rarely matches.',
    'That compression is also why the map pack is fought over. Three listings sit above the organic results and absorb a disproportionate share of the clicks and the calls. Ranking inside them is not a matter of having a website that ranks well. It is a separate system with its own signals, its own profile to manage, and its own reasons to demote a business without warning.',
    'The mechanics are more knowable than most businesses assume. Local results are driven by how well a listing matches the search, how close the business is to the searcher, and how well known the business is. Two of those three are directly improvable: through a complete profile, consistent business information across the web, a current review history, and content on your own site that establishes what you do and where.',
  ],
  problemsHeading: 'Why Local Rankings Stall',
  problems: [
    {
      title: 'The Business Profile Is Claimed, Not Managed',
      body: 'A profile with a category chosen once, no service list, no product entries, a handful of photos from launch and no posts is technically live and competitively invisible. Completeness is both a ranking input and a conversion factor. The listing is often the only thing a searcher looks at before choosing, and it is doing that work whether or not you maintain it.',
    },
    {
      title: 'Business Information Disagrees Across the Web',
      body: 'Name, address and phone details drift as businesses move, rebrand or change numbers. Old directory entries, unclaimed aggregator records and outdated listings persist, and the inconsistency undermines confidence that your business is what and where it claims to be. This is unglamorous work that quietly caps how prominent a listing is able to become.',
    },
    {
      title: 'Reviews Are Collected Sporadically or Not at All',
      body: 'A business with a dozen reviews from three years ago competes badly against one with a steady stream of recent ones. Review volume, recency, rating and whether the owner responds all feed local prominence and, more importantly, the decision a person makes while comparing three listings side by side on a phone.',
    },
    {
      title: 'Location Pages Are Duplicated Templates',
      body: 'Pages generated by swapping a place name into the same paragraph add no information and can be treated as thin content. Each page needs a genuine reason to exist: the services delivered there, the specific problems solved, proof from work completed nearby, and the details a person actually wants before they pick up the phone.',
    },
  ],
  includedHeading: 'What Local SEO Covers',
  includedIntro:
    'Local visibility is an infrastructure problem before it is a content problem, so the work is sequenced to fix suppression before adding signal.',
  included: [
    {
      title: 'Google Business Profile Optimization',
      body: 'Primary and secondary category selection, complete service and product listings, attributes, service areas, hours including exceptions, description, booking and messaging settings, and a photo and post cadence. Every field is both a relevance signal and a conversion surface.',
    },
    {
      title: 'Citation Audit and NAP Consistency',
      body: 'Identification and correction of business listings across directories, data aggregators and industry-specific platforms, with duplicates removed and information standardized. Consistency is what allows search engines to consolidate scattered mentions into one confident entity.',
    },
    {
      title: 'Review Generation and Response System',
      body: 'A repeatable process for requesting reviews at the right point in the customer relationship, routed through the tools your team already uses, plus response templates and a monitoring cadence so no review sits unanswered for weeks.',
    },
    {
      title: 'Location and Service-Area Page Architecture',
      body: 'Pages built with genuine differentiation: services delivered, local proof, relevant questions answered and internal links to the service pages they support. Structured to scale as coverage grows, without generating near-duplicate content that dilutes the whole set.',
    },
    {
      title: 'Local Structured Data',
      body: 'LocalBusiness markup, or the appropriate subtype, carrying address, geo coordinates, opening hours, service area, price range and aggregate rating, kept consistent with the profile and revalidated after every template change.',
    },
    {
      title: 'Localized On-Site Content and Internal Linking',
      body: 'Service pages written to establish what you do and the areas you cover, connected to supporting content that answers the practical questions people ask before calling. Internal links direct authority toward the pages that need to rank locally.',
    },
    {
      title: 'Call Tracking and Local Conversion Measurement',
      body: 'Dynamic number insertion on the website, profile insights covering calls and direction requests, and form attribution, so contact generated by local search is measured rather than assumed. Implemented in a way that does not break citation consistency.',
    },
  ],
  approachHeading: 'How We Build Local Visibility',
  approach: [
    {
      step: '01',
      title: 'Local Audit and Competitive Grid',
      body: 'We assess profile completeness, category alignment, citation accuracy, review profile and on-site local signals, then map how visibility changes across a grid of points around the business. Local rank is not a single number; it varies with where the searcher is standing.',
    },
    {
      step: '02',
      title: 'Fix the Foundation',
      body: 'Profile fields completed and corrected, duplicate listings resolved, citations standardized, structured data implemented, and any category or service-area misconfiguration repaired. These corrections often move visibility before new content is written, because they remove suppression rather than add signal. It is the cheapest work in the engagement and often the most productive.',
    },
    {
      step: '03',
      title: 'Build the Review Engine',
      body: 'A process that fits how your team actually operates: when the request goes out, who sends it, what it says, how responses are handled and how negative feedback reaches someone internally before it becomes public. Review velocity only sustains itself when the process is realistic.',
    },
    {
      step: '04',
      title: 'Build Local Content',
      body: 'Service and area pages written with real substance, supported by content answering the questions that precede a call: cost expectations, timelines, qualifications, process. This gives the profile something authoritative to point at and earns the organic positions beneath the map pack.',
    },
    {
      step: '05',
      title: 'Measure by Calls, Not Positions',
      body: 'Reporting combines grid rank tracking, profile insights covering calls, direction requests and website clicks, tracked call volume and form enquiries. The measure of local SEO is contact volume from the areas you serve, not an average position inside a rank tracking tool.',
    },
  ],
  outcomesHeading: 'What Better Local Visibility Produces',
  outcomesIntro:
    'Described as business effects rather than as invented figures, because local performance varies enormously by category and competition.',
  outcomes: [
    {
      title: 'Enquiries From People Ready to Act',
      body: 'Local search intent sits close to the decision. Visibility at that moment produces contact from people who need the service now, rather than from researchers who might need something eventually.',
    },
    {
      title: 'A Listing That Sells Before the Click',
      body: 'A complete profile with current photos, clear services, honest hours and recent reviews does persuasion work inside the results page itself, which is where a growing share of the decision now happens.',
    },
    {
      title: 'Reputation as a Process, Not a Scramble',
      body: 'Reviews arrive consistently because a system produces them. The rating stays current, responses get handled, and the business stops depending on whichever customer felt strongly enough to write something unprompted.',
    },
    {
      title: 'Coverage That Extends Beyond the Doorstep',
      body: 'Structured area pages and correct profile configuration extend visibility across the areas you genuinely serve, rather than limiting it to searches happening within a few streets of your address. That widens the catchment without opening another location.',
    },
  ],
  deepDive: [
    {
      heading: 'How the Map Pack Ranks: Relevance, Distance and Prominence',
      paragraphs: [
        'Google describes local ranking through three factors: relevance, meaning how well a profile matches what was searched; distance, meaning how far the business is from the searcher or the searched area; and prominence, meaning how well known and well regarded the business is. Only one of those is fixed. Relevance and prominence are both directly improvable, and most businesses have barely started on either of them. The ones that work on both are the ones that stay in the pack.',
        'Relevance is largely a completeness problem. The primary category carries substantial weight and is frequently chosen carelessly, sometimes years ago by someone who has since left. Secondary categories, the services list, product entries, attributes and the business description all give the system more to match against. A profile listing twenty specific services can be relevant to twenty specific queries. A profile with one category and a phone number can be relevant to one.',
        'Prominence is built from signals outside the profile: review volume, rating and recency, citation consistency, links and mentions from other sites, and the authority of the website attached to the listing. This is where local SEO and conventional SEO stop being separate disciplines. A site with strong technical foundations, real content and earned links makes its associated listing more prominent, which is why local SEO, conventional SEO and the underlying web design should be run as one program rather than bought from three suppliers.',
      ],
    },
    {
      heading: 'Reviews, Reputation Signals and Response Discipline',
      paragraphs: [
        'Review velocity matters as much as review count. A steady arrival of recent reviews signals an operating business with current customers; a large number of old reviews signals history. Both the ranking system and the person comparing three listings weigh recency, and a business that collected reviews intensively during one campaign and then stopped looks progressively worse than one collecting a few every month. Consistency beats intensity here, and it is easier to resource.',
        'The mechanism that makes this sustainable is process, not enthusiasm. The request has to be triggered by something that already happens, sent by someone the customer recognises, timed to the moment satisfaction is highest, and easy enough to complete on a phone in under a minute. Where a CRM or marketing automation platform exists, the request should fire automatically at job completion or invoice payment rather than depend on somebody remembering.',
        'Responses are the part most businesses skip. Replying to positive reviews reinforces the behavior and adds relevant language to the listing. Replying calmly to negative reviews is read by every future prospect who scrolls past, and a measured response to a difficult review often persuades more effectively than an unbroken run of five-star ratings, which readers increasingly discount. Response discipline is reputation management performed in public, and it costs nothing beyond the time to write a considered paragraph.',
      ],
    },
    {
      heading: 'Location Pages, Service Areas and Measuring What Local Search Produces',
      paragraphs: [
        'Location pages fail when they are duplication with the place name swapped. They work when each has something specific to say: the services genuinely delivered there, response and travel expectations, relevant regulatory or seasonal considerations, proof from work completed nearby, and answers to the questions people in that area actually ask. If a page could serve any area through find-and-replace, it should not exist. One substantive page beats twenty thin ones and carries none of the filtering risk.',
        'Service-area businesses without a public premises need a different configuration: the profile set to hide the address, service areas defined honestly rather than expansively, and on-site content that establishes coverage without claiming an office that does not exist. Overstating coverage is a common and counterproductive tactic, because it dilutes relevance across areas where the business will never rank and can trigger a suspension that removes the listing altogether. Reinstatement is slow, and the calls lost in the meantime never arrive.',
        'Measurement is where local SEO earns or loses its budget. Profile insights show calls, direction requests, messages and website clicks. Dynamic number insertion attributes website calls to their source, which separates organic local demand from Google Ads and every other paid channel. Grid-based rank tracking shows how visibility varies across the area instead of reporting one misleading average. Feeding those calls into a CRM, with outcome logging, is what finally connects local visibility to booked work rather than to activity. That connection is what turns a local SEO budget into a defensible line item.',
      ],
    },
  ],
  faqs: [
    {
      question: 'What is the difference between local SEO and regular SEO?',
      answer:
        'Local SEO targets the map pack and location-qualified searches, and it depends on signals conventional SEO does not use: Google Business Profile completeness, proximity to the searcher, citation consistency and review activity. Conventional SEO targets the organic listings through technical health, content and links. They overlap, because a stronger website raises listing prominence, but a business can rank organically and still be absent from the map results entirely.',
    },
    {
      question: 'How important is the Google Business Profile compared to the website?',
      answer:
        'For searches with local intent the profile often matters more, because it appears above the organic results and carries the phone number, hours, reviews and directions that complete the enquiry without any website visit. The website still matters considerably: it supplies the prominence signals and the content that make the profile competitive, and it serves buyers who want to research properly before calling anyone.',
    },
    {
      question: 'Can we rank in areas where we have no physical address?',
      answer:
        'In the map pack, only within a limited radius, because distance from the searcher is a ranking factor you cannot influence. Beyond that radius the realistic route is organic: substantive service-area pages, relevant content and authority signals that earn positions beneath the map results. Creating fake addresses to extend map coverage risks suspension of the listing, which costs far more than the visibility it briefly gains.',
    },
    {
      question: 'How do we get more reviews without breaking the rules?',
      answer:
        'By asking every customer at the point of highest satisfaction, through a process that runs automatically rather than depending on someone remembering to ask. Requests must go to all customers, not only the ones expected to be positive, and offering incentives in exchange for reviews is prohibited on most platforms. The mechanics that matter are timing, ease of completion, and the request coming from a person the customer dealt with.',
    },
    {
      question: 'Will call tracking numbers damage our local rankings?',
      answer:
        'Not when implemented correctly. Use dynamic number insertion so the tracked number appears only to website visitors while the consistent business number remains in the page source and in structured data, and keep the primary number on the Business Profile unchanged, adding a tracked number as a secondary if required. Problems arise when tracked numbers are propagated into citations, which breaks the consistency local ranking depends on.',
    },
    {
      question: 'How long does local SEO take to work?',
      answer:
        'Profile and citation corrections can influence visibility within weeks, which makes local SEO faster than conventional organic search in most categories. Building review volume, earning prominence and ranking location pages takes months of consistent effort. The realistic pattern is early movement from removing whatever was suppressing the listing, followed by gradual gains as reviews, content and authority accumulate over time.',
    },
  ],
  relatedServices: ['seo', 'google-ads', 'web-design', 'crm-systems'],
  relatedIndustries: ['home-services', 'dental', 'medical', 'law-firms', 'real-estate'],
  ctaHeading: 'Own the Searches That End in a Phone Call',
  ctaBody:
    'Tell us the services you want to be called for and the areas you cover. We will map current visibility across that footprint and show you exactly what is holding the listing back.',
}

export default service
