import type { ServiceSeed } from '@/seed/types'

const service: ServiceSeed = {
  slug: 'seo',
  category: 'get-found',
  title: 'SEO',
  navLabel: 'SEO',
  tagline: 'An acquisition channel that keeps producing after the invoice is settled.',
  icon: 'Search',
  metaTitle: 'SEO Services Built to Compound | Digital Kingz',
  metaDescription:
    'SEO built as a compounding acquisition channel: technical foundations, content architecture, entity authority, structured data and visibility in AI search.',
  heroEyebrow: 'Grow / SEO',
  heroHeading: 'The Only Channel That Gets Cheaper Over Time',
  heroSubheading:
    'Technical foundations, content architecture and entity authority, built so the same pages keep producing enquiries long after the work that created them was paid for.',
  intro: [
    'Paid media stops the moment the budget does. Every lead has a price, and that price is set by an auction you do not control against competitors who can outbid you at any time. SEO behaves differently. A page that earns its position keeps producing enquiries after the invoice is settled, and the cost per lead falls for every month it continues to rank.',
    'That is also why SEO is misunderstood. It is a capital investment with a lag, not a monthly service that produces immediate return. The first few months usually build the asset. The return arrives afterwards and continues, which makes SEO hard to justify against a paid campaign that shows results this week, and considerably more valuable across a three-year horizon.',
    'The work itself is unglamorous: making the site technically crawlable, structuring content so a search engine can tell what the business is authoritative about, earning citations from sources that already carry authority, and answering the questions buyers actually ask. None of it is a trick, which is why it survives the algorithm updates that eliminate whatever the current shortcut happens to be.',
  ],
  problemsHeading: 'Why Most SEO Investment Underperforms',
  problems: [
    {
      title: 'Keywords Are Chosen by Volume, Not by Intent',
      body: 'Ranking for a high-volume term that attracts researchers rather than buyers produces traffic and no pipeline. Commercial intent, not search volume, determines whether a ranking is worth having. A page that ranks for a specific problem-and-solution query with modest volume will usually out-earn a broad informational term carrying ten times the impressions.',
    },
    {
      title: 'Content Exists as a Pile, Not an Architecture',
      body: 'Publishing individual articles with no structural relationship between them produces a blog, not authority. Search engines model topics through connected pages: a service page supported by explanatory content, linked to the industries it serves and the case studies that prove it. Unconnected posts compete with each other and consolidate nothing at all.',
    },
    {
      title: 'Technical Foundations Cap the Work',
      body: 'Slow pages, client-side rendering that hides content from crawlers, duplicate URLs generated by filters and parameters, broken canonical tags, missing structured data and unclear internal linking all limit what any content investment can achieve. Content strategy applied to a technically compromised site is money spent on a foundation that cannot hold it.',
    },
    {
      title: 'Reporting Measures Rankings Instead of Revenue',
      body: 'A report full of position changes and impression counts tells you nothing about whether the investment worked. Rankings are an intermediate measure. What matters is which pages produce qualified enquiries, what those enquiries are worth, and how that compares against what the same money would have returned in paid media.',
    },
  ],
  includedHeading: 'What an SEO Engagement Includes',
  includedIntro:
    'Sequenced by dependency. Nothing downstream is worth paying for until the foundation underneath it can support the weight.',
  included: [
    {
      title: 'Technical SEO Audit and Remediation',
      body: 'Crawlability, indexation, rendering, page speed against Core Web Vitals field data, canonicalization, redirect hygiene, XML sitemaps, robots directives, pagination and faceted URL handling. Findings are ranked by traffic impact and then fixed, not simply documented in a spreadsheet and handed over.',
    },
    {
      title: 'Keyword and Intent Mapping',
      body: 'Search demand mapped to buying stage and to the single page that should own it, so every commercially valuable query has exactly one destination. This produces the page inventory the site needs and prevents two of your own pages competing for the same term.',
    },
    {
      title: 'Content Architecture and Internal Linking',
      body: 'Service pages, industry pages, supporting articles and case studies structured as connected topic clusters with deliberate internal links and descriptive anchor text. Authority flows toward the pages that convert rather than pooling on a blog index nobody visits.',
    },
    {
      title: 'On-Page and Entity Optimization',
      body: 'Titles, headings, semantic depth and the entity relationships that define what the business is: services offered, industries served, technologies used, areas covered. Search engines and AI systems both resolve businesses as entities, and consistency across sources is what makes that resolution confident.',
    },
    {
      title: 'Structured Data Implementation',
      body: 'schema.org markup for Organization, Service, FAQPage, Article, BreadcrumbList and Review where applicable, validated and monitored after template changes. Structured data makes content machine-readable, supports rich results, and gives AI systems an unambiguous description to work from.',
    },
    {
      title: 'Digital PR and Authority Building',
      body: 'Earning citations and links from sources with genuine authority in your sector: industry publications, associations, partners, data-led assets and expert commentary. No purchased link networks, because the recovery cost of a manual action exceeds any short-term gain they produce.',
    },
    {
      title: 'Measurement Tied to Pipeline',
      body: 'Search Console and analytics configured to report by landing page and intent, joined to conversion events and, where the CRM allows, to closed revenue. Reporting answers which pages produce business, not which keywords moved two positions since last month.',
    },
  ],
  approachHeading: 'How We Run SEO',
  approach: [
    {
      step: '01',
      title: 'Audit and Baseline',
      body: 'Full technical crawl, index coverage analysis, rendering checks, content inventory, backlink profile review and competitor gap analysis. We establish the starting position precisely, because without a baseline nobody can distinguish genuine progress from seasonality or from a competitor having a bad quarter.',
    },
    {
      step: '02',
      title: 'Fix the Foundation',
      body: 'Technical remediation comes first: rendering, speed, duplication, redirects, structured data and internal linking. These changes usually produce the earliest movement, because they release value from pages that already exist and are already close enough to ranking to benefit. It is also the cheapest phase, because nothing new has to be written.',
    },
    {
      step: '03',
      title: 'Build the Architecture',
      body: 'We define the page inventory, assign each commercially relevant query to a single owner page, and build the cluster structure connecting services to industries and to supporting content. This work determines the ceiling on everything published afterwards, so it happens before the writing starts.',
    },
    {
      step: '04',
      title: 'Publish and Earn Authority',
      body: 'Content is produced against the architecture in priority order by commercial value, with genuine depth on subjects the business can speak to credibly. Authority building runs alongside it, targeting the publications, associations and partners your buyers and your sector already trust.',
    },
    {
      step: '05',
      title: 'Measure, Refine, Compound',
      body: 'Monthly review of rankings, coverage, page-level conversions and pipeline contribution. Underperforming pages get rewritten or consolidated, winning pages get expanded and internally reinforced, and the roadmap adjusts to what the data shows rather than to the original assumption. Consolidation is underrated: fewer, stronger pages usually beat more of them.',
    },
  ],
  outcomesHeading: 'What Compounding Looks Like',
  outcomesIntro:
    'Described qualitatively and on purpose. SEO does not produce a guaranteed number, and anyone offering one is selling something other than SEO.',
  outcomes: [
    {
      title: 'Acquisition Cost That Falls Instead of Rising',
      body: 'Pages that hold their positions keep producing enquiries without further spend. Cost per lead from organic search declines as the asset matures, which is the opposite of what happens in a paid auction over the same period.',
    },
    {
      title: 'Demand You Are Currently Invisible For',
      body: 'Buyers searching with problem language, comparison language and specific service terms find you at the point they are deciding, rather than only when they already know your name and search for it directly.',
    },
    {
      title: 'Negotiating Room in Paid Media',
      body: 'Organic coverage on your core commercial terms means paid budget can be pointed at campaigns where it earns more, instead of defending positions you could hold for nothing once the pages mature.',
    },
    {
      title: 'Authority That Transfers to AI Answers',
      body: 'The same entity clarity, structured data and citable content that earns search rankings is what makes a business quotable when someone asks an AI assistant for a recommendation in your category.',
    },
  ],
  deepDive: [
    {
      heading: 'Technical SEO and Content Architecture: The Two Foundations',
      paragraphs: [
        'Technical SEO decides whether your content can be found, rendered, understood and indexed efficiently. That means server-rendered HTML rather than content assembled by client-side JavaScript, a clean URL structure without duplicate paths generated by filters or tracking parameters, correct canonical tags, sitemaps that reflect reality, and page speed inside Core Web Vitals thresholds. None of this makes content rank on its own. All of it caps what content can achieve, which is why we sequence it first.',
        'Content architecture is the second foundation. Search engines do not evaluate pages in isolation; they build a model of what a site is about from how its pages relate to one another. A service page that links to the industries it serves, the case studies that prove it and the explanatory content supporting it forms a cluster that reads as expertise. Fifty unconnected blog posts read as volume. The difference is internal linking with descriptive anchor text and a deliberate hierarchy.',
        'This is where SEO overlaps with web design and web development rather than sitting downstream of them. The sitemap is a design artifact. Rendering strategy is a development decision. Internal links are a template concern. When those choices are made without search in mind, the SEO engagement begins by paying to undo them, which is the most avoidable cost in the entire discipline. It is also why we would rather be in the room during architecture than arrive after launch.',
      ],
    },
    {
      heading: 'Entity Authority and Being Cited by AI Search',
      paragraphs: [
        'Search is no longer only a list of links. ChatGPT, Claude, Gemini and Perplexity now answer commercial questions directly, and the businesses named in those answers receive the recommendation a ranked listing used to represent. Generative engine optimization, often shortened to GEO, is the practice of making a business legible and quotable to those systems. It overlaps heavily with good SEO, but the emphasis differs in ways that are worth understanding properly.',
        'AI systems resolve businesses as entities rather than as keyword matches. That resolution is strengthened by consistency: the same organization name, description, services, industries and contact details expressed the same way across your site, your structured data, your Google Business Profile, industry directories and third-party mentions. Organization and Service schema, clear service definitions, FAQ content that answers questions in complete self-contained sentences, and a well-connected knowledge architecture all make a business easier to cite confidently.',
        'The practical differences are specific. AI systems favor content that states its answer plainly near the top rather than burying it beneath an introduction. They favor original data, defined terminology and clear attribution over rewritten consensus. They depend on being able to extract a claim without ambiguity. Writing content that genuinely helps a careful reader turns out to be the same thing as writing content a model can quote, which is a rare alignment of incentives.',
      ],
    },
    {
      heading: 'SEO Economics and What Happens After the Click',
      paragraphs: [
        'The honest case for SEO is a cash flow argument. Investment is front-loaded and returns are delayed, typically arriving as a curve rather than a step. Paid media inverts that: immediate return, no accumulation, and a cost that rises with competition. Most businesses need both, and the useful question is not which channel is better but what proportion of acquisition should be owned rather than rented. A business renting all of its demand has no asset to show for years of spend.',
        'Rankings are also only half the transaction. Traffic arriving on a page that fails to convert is a rounding error in a report. Search performance and conversion optimization are the same investment viewed from two ends, and a business is usually better served by improving the conversion rate of pages that already rank than by chasing additional positions with a broken destination waiting at the end. The traffic already exists; the page is the part that fails.',
        'The chain continues past the form. An enquiry that sits in a shared inbox for two days is worth less than one routed instantly into a CRM, qualified, and followed up automatically. Your website should not exist in isolation, and neither should your search channel: branding makes you memorable, SEO makes you findable, conversion turns visits into enquiries, and CRM systems and AI automation determine how many of those enquiries become revenue.',
      ],
    },
  ],
  faqs: [
    {
      question: 'How long does SEO take to produce results?',
      answer:
        'Meaningful movement typically begins within three to six months, with compounding returns after that, though technical fixes on an established site can produce earlier gains by releasing value from pages that already rank. The timeline depends on domain history, competition, the state of the technical foundation and publishing capacity. Anyone promising top positions within weeks is either targeting terms nobody searches or using tactics that carry recovery risk.',
    },
    {
      question: 'Is SEO better than paid advertising?',
      answer:
        'They solve different problems, and most businesses need both. Paid media buys immediate, controllable volume and stops the moment the budget stops. SEO builds an asset that keeps producing after spend ends, but takes months to mature. The practical approach is to use paid channels for immediate pipeline and to test which messages and terms convert, then invest SEO effort in owning the terms that proved commercially valuable.',
    },
    {
      question: 'How do you get a business mentioned in AI search results?',
      answer:
        'By making the business unambiguous to machines and genuinely worth citing. That means consistent entity information across your site, structured data and third-party sources, Organization and Service schema, content that answers questions directly in self-contained sentences, original insight rather than rewritten consensus, and mentions on sources those systems already trust. There is no submission process. AI visibility is earned through the same clarity that earns search visibility.',
    },
    {
      question: 'Do we need to publish content every week?',
      answer:
        'No. Cadence matters far less than coverage and quality. A business with twelve genuinely useful pages covering its services, its industries and the questions buyers ask will outperform one publishing weekly filler. What matters is whether every commercially relevant query has a page that deserves to own it, and whether existing pages stay accurate. Consistent publishing helps once that architecture exists, not before.',
    },
    {
      question: 'What happens to our rankings if we stop?',
      answer:
        'They decline gradually rather than disappearing, and the rate depends on how competitive your category is. Technical foundations and earned authority persist for a while, but competitors keep publishing, content ages out of accuracy, and technical drift accumulates. SEO is closer to holding a market position than to buying a one-off outcome, which is why we prefer to be direct about it being an ongoing investment.',
    },
    {
      question: 'How do you report on SEO performance?',
      answer:
        'By landing page and commercial intent, joined to conversion events rather than to keyword positions alone. Reporting covers organic sessions and enquiries by page, index coverage and technical health, movement on terms that carry buying intent, authority signals earned, and where the CRM allows it, pipeline value attributed to organic search. Position tracking is included as a diagnostic, not as the headline measure of success.',
    },
  ],
  relatedServices: ['local-seo', 'conversion-optimization', 'web-development', 'google-ads'],
  relatedIndustries: ['law-firms', 'medical', 'b2b', 'professional-services'],
  ctaHeading: 'Own the Demand You Currently Rent',
  ctaBody:
    'Send us your domain and the terms that matter commercially. We will come back with what is capping performance now, what the realistic ceiling is, and the sequence that gets you there.',
}

export default service
