import type { Metadata } from 'next'
import { LegalPage } from '@/components/sections/LegalPage'
import { getSiteSettings } from '@/lib/payload'
import { buildMetadata } from '@/lib/seo'

export const revalidate = 86400

export const metadata: Metadata = buildMetadata({
  title: 'Privacy Policy',
  description:
    'How Digital Kingz collects, uses, stores and protects personal information submitted through digitalkingz.com.',
  path: '/privacy',
})

const UPDATED = '7 August 2026'

export default async function PrivacyPage() {
  const settings = await getSiteSettings()
  const email = settings.email ?? 'hello@digitalkingz.com'

  return (
    <LegalPage
      title="Privacy Policy"
      intro="This policy explains what personal information we collect through this website, why we collect it, how long we keep it and what rights you have over it."
      updated={UPDATED}
      crumbs={[
        { name: 'Home', path: '/' },
        { name: 'Privacy Policy', path: '/privacy' },
      ]}
      sections={[
        {
          heading: 'Who we are',
          paragraphs: [
            `${settings.legalName ?? 'Digital Kingz Development'} operates digitalkingz.com and is the controller of personal information collected through it. You can reach us at ${email} for any question about this policy or about information we hold.`,
          ],
        },
        {
          heading: 'Information we collect',
          paragraphs: [
            'We collect information in two ways: information you give us directly, and limited technical information collected automatically when you use the site.',
          ],
          bullets: [
            'Information you submit through the contact form: your name, email address, phone number if provided, business name, website, industry, the services you are interested in, budget range, timeline and the description of your project.',
            'Marketing attribution data attached to your enquiry: the page you submitted from, the referring website, and any campaign parameters present in the URL such as utm_source, utm_medium, utm_campaign or a Google click identifier.',
            'Technical information generated by your visit, including IP address, browser type and pages viewed, used for security, rate limiting and aggregate analytics.',
            'Any information you choose to include when you email or call us directly.',
          ],
        },
        {
          heading: 'Why we use it',
          bullets: [
            'To respond to your enquiry and assess whether we are a suitable fit for your project.',
            'To prepare proposals and deliver services if you become a client.',
            'To understand which marketing channels produce genuine enquiries, so we do not continue paying for those that do not.',
            'To protect the site from automated abuse, including rate limiting repeated submissions from a single address.',
            'To meet legal, accounting and record-keeping obligations.',
          ],
        },
        {
          heading: 'Our lawful basis',
          paragraphs: [
            'Where you submit an enquiry, we process your information on the basis of your consent and of taking steps at your request prior to entering into a contract. Where we process technical information for security and aggregate analytics, we do so on the basis of our legitimate interest in operating a secure and effective website. You can withdraw consent at any time by contacting us.',
          ],
        },
        {
          heading: 'Marketing',
          paragraphs: [
            'The contact form is not a mailing list signup. Submitting an enquiry does not subscribe you to a newsletter or an automated sequence. If we ever introduce a separate marketing list it will require its own explicit opt in, and every message will carry an unsubscribe link.',
          ],
        },
        {
          heading: 'Who we share it with',
          paragraphs: [
            'We do not sell personal information, and we do not share it with third parties for their own marketing purposes. We share information only with service providers that help us operate the business, and only to the extent needed.',
          ],
          bullets: [
            'Our hosting and infrastructure provider, which stores the database containing enquiries.',
            'Our transactional email provider, which delivers enquiry notifications to our team.',
            'Our customer relationship management or workflow automation platform, where enquiries are recorded so they can be followed up.',
            'Professional advisors and authorities where we are required to disclose information by law.',
          ],
        },
        {
          heading: 'International transfers',
          paragraphs: [
            'Some of our service providers may process data outside your country of residence. Where that happens we rely on the safeguards those providers have in place, including standard contractual clauses where applicable. You can ask us which providers are involved and where they process data.',
          ],
        },
        {
          heading: 'How long we keep it',
          paragraphs: [
            'Enquiries that do not result in an engagement are retained for up to 24 months, so that we have context if you come back to us, and are then deleted. Records relating to clients are retained for as long as the relationship continues and afterwards for the period required by applicable tax and contract law. Technical logs are retained for a short period for security purposes.',
          ],
        },
        {
          heading: 'Your rights',
          paragraphs: [
            'Subject to the law that applies to you, you can ask us to provide a copy of the personal information we hold about you, correct it if it is inaccurate, delete it, restrict how we use it, or object to a particular use. You can also ask us to provide your information in a portable format.',
            `To make a request, email ${email}. We will respond within the timeframe required by applicable law. If you are not satisfied with our response, you have the right to complain to the data protection authority in your jurisdiction.`,
          ],
        },
        {
          heading: 'Cookies and analytics',
          paragraphs: [
            'This site does not set advertising or cross-site tracking cookies of its own. Where analytics are enabled, they are used to understand aggregate site usage rather than to build a profile of individual visitors. If in future we introduce tools that require consent under the law applicable to you, we will ask for that consent before those tools load.',
          ],
        },
        {
          heading: 'Security',
          paragraphs: [
            'Information submitted through this site is transmitted over an encrypted connection and stored in a database with restricted access. Access to enquiry data is limited to people who need it to respond to you. No system is perfectly secure, but we take reasonable technical and organisational measures appropriate to the sensitivity of the information involved.',
          ],
        },
        {
          heading: 'Changes to this policy',
          paragraphs: [
            'We may update this policy as our services or legal obligations change. The date at the top of this page reflects the most recent revision. Material changes will be highlighted on this page.',
          ],
        },
        {
          heading: 'Contact',
          paragraphs: [
            `Questions, requests or complaints about this policy can be sent to ${email} and will be handled by a person, not a queue.`,
          ],
        },
      ]}
    />
  )
}
