/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    people: Person;
    taxonomies: Taxonomy;
    services: Service;
    industries: Industry;
    posts: Post;
    categories: Category;
    authors: Author;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    people: PeopleSelect<false> | PeopleSelect<true>;
    taxonomies: TaxonomiesSelect<false> | TaxonomiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Profiles at /people/[slug]. A profile is only worth indexing once it has a bio, an image and at least one verifiable source.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * Source system identifier. The importer matches on this before it matches on slug.
   */
  externalId?: string | null;
  /**
   * Canonical URL segment: /people/[slug].
   */
  slug: string;
  /**
   * Only published profiles are routable and appear in the sitemap.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * 0-100, set by the importer. The quality threshold for indexing is applied against this.
   */
  completeness?: number | null;
  name: string;
  /**
   * Legal or birth name, stage names. Comma separated. Used by search.
   */
  alternateNames?: string | null;
  usernamePrimary?: string | null;
  /**
   * A person can legitimately be both.
   */
  personTypes: ('influencer' | 'public-figure')[];
  gender?: string | null;
  generation?: string | null;
  dateOfBirth?: string | null;
  nationality?: string | null;
  city?: string | null;
  /**
   * Denormalised from the country taxonomy for fast filtering.
   */
  countryCode?: string | null;
  countries?: (number | Taxonomy)[] | null;
  regions?: (number | Taxonomy)[] | null;
  industries?: (number | Taxonomy)[] | null;
  sports?: (number | Taxonomy)[] | null;
  platforms?: (number | Taxonomy)[] | null;
  topics?: (number | Taxonomy)[] | null;
  genres?: (number | Taxonomy)[] | null;
  professions?: (number | Taxonomy)[] | null;
  languages?: (number | Taxonomy)[] | null;
  /**
   * Shown on the result card and used for the default breadcrumb.
   */
  primaryIndustry?: (number | null) | Taxonomy;
  sportRole?: string | null;
  /**
   * Comma separated. Free text, not yet a taxonomy.
   */
  niches?: string | null;
  audienceType?: string | null;
  audienceScope?: string | null;
  /**
   * One or two sentences. Used on cards and in meta descriptions.
   */
  bioShort?: string | null;
  bioLong?: string | null;
  knownFor?: string | null;
  notableWork?: string | null;
  awards?: string | null;
  organizations?: string | null;
  brands?: string | null;
  profileImage?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  socialProfiles?:
    | {
        platform: number | Taxonomy;
        handle?: string | null;
        url?: string | null;
        followers?: number | null;
        engagementRate?: number | null;
        /**
         * A follower count with no date on it is not a fact, it is a rumour.
         */
        lastCheckedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  websiteUrl?: string | null;
  wikipediaUrl?: string | null;
  officialSourceUrl?: string | null;
  verified?: boolean | null;
  verificationDate?: string | null;
  claimed?: boolean | null;
  /**
   * Internal. Never rendered on the public page.
   */
  editorialNotes?: string | null;
  /**
   * Controls the <title>, meta description and social preview for this page.
   */
  seo: {
    /**
     * Aim for 50-60 characters. Google truncates beyond roughly 60.
     */
    metaTitle: string;
    /**
     * Aim for 140-158 characters. Written to earn the click, not to describe.
     */
    metaDescription: string;
    /**
     * Optional. Falls back to the generated brand card if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Countries, industries, sports, platforms and the other ways people are classified. Each row can become a landing page once it holds enough profiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies".
 */
export interface Taxonomy {
  id: number;
  /**
   * Determines the URL segment this term lives under.
   */
  type:
    | 'person-type'
    | 'country'
    | 'region'
    | 'industry'
    | 'sport'
    | 'platform'
    | 'topic'
    | 'genre'
    | 'profession'
    | 'language'
    | 'audience-type';
  /**
   * Lowercase, hyphenated. Unique within its type.
   */
  slug: string;
  title: string;
  /**
   * Intro copy for the landing page. A term with no description should not be indexed — it is a thin page.
   */
  description?: string | null;
  /**
   * ISO 3166-1 alpha-2, used for flags and hreflang.
   */
  countryCode?: string | null;
  /**
   * Optional. Lets countries roll up into a region.
   */
  parent?: (number | null) | Taxonomy;
  /**
   * Maintained by the importer. Drives whether this term is worth a landing page.
   */
  personCount?: number | null;
  /**
   * Surface this term on the People homepage.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images used across the site. Alt text is required for accessibility and SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows, for screen readers and image search. Leave decorative images with a short factual description.
   */
  alt: string;
  /**
   * Optional. Displayed under the image where the layout supports it.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Service pages live at /services/[slug]. Each one is a standalone ranking and conversion asset.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from title if left blank.
   */
  slug: string;
  /**
   * A lucide-react icon name in PascalCase, e.g. MapPin. See lucide.dev/icons.
   */
  icon: string;
  /**
   * Lower numbers appear first in navigation, hubs and the sitemap.
   */
  order: number;
  /**
   * Groups the service in the mega menu and on the services hub.
   */
  category: 'build' | 'get-found' | 'convert' | 'automate';
  title: string;
  /**
   * Short label for navigation and cards.
   */
  navLabel: string;
  /**
   * One sentence. Shown on service cards and in the mega menu.
   */
  tagline: string;
  hero: {
    eyebrow: string;
    heading: string;
    subheading: string;
  };
  /**
   * Separate paragraphs with a blank line.
   */
  intro: string;
  problemsHeading: string;
  problems: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  includedHeading: string;
  includedIntro: string;
  included: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  approachHeading: string;
  approach: {
    /**
     * e.g. 01
     */
    step: string;
    title: string;
    body: string;
    id?: string | null;
  }[];
  outcomesHeading: string;
  outcomesIntro: string;
  /**
   * Qualitative outcomes only. Never publish a performance number that has not been verified against real client data.
   */
  outcomes: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  /**
   * Carries the semantic SEO weight of the page. Each heading renders as an H2.
   */
  deepDive?:
    | {
        heading: string;
        /**
         * Separate paragraphs with a blank line.
         */
        paragraphs: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as FAQPage structured data. Answer the question directly in the first sentence so AI answer engines can lift it cleanly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Drives the internal linking block at the foot of the page.
   */
  relatedServices?: (number | Service)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  cta: {
    heading: string;
    body: string;
  };
  /**
   * Controls the <title>, meta description and social preview for this page.
   */
  seo: {
    /**
     * Aim for 50-60 characters. Google truncates beyond roughly 60.
     */
    metaTitle: string;
    /**
     * Aim for 140-158 characters. Written to earn the click, not to describe.
     */
    metaDescription: string;
    /**
     * Optional. Falls back to the generated brand card if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Industry pages live at /industries/[slug]. Each must explain problems specific to that vertical, not a renamed generic page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from title if left blank.
   */
  slug: string;
  /**
   * A lucide-react icon name in PascalCase, e.g. MapPin. See lucide.dev/icons.
   */
  icon: string;
  /**
   * Lower numbers appear first in navigation, hubs and the sitemap.
   */
  order: number;
  title: string;
  navLabel: string;
  tagline: string;
  hero: {
    eyebrow: string;
    heading: string;
    subheading: string;
  };
  /**
   * Separate paragraphs with a blank line.
   */
  intro: string;
  challengesHeading: string;
  challengesIntro: string;
  challenges: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  buyerBehaviourHeading: string;
  /**
   * Separate paragraphs with a blank line. This section is what makes the page vertical-specific rather than generic.
   */
  buyerBehaviour: string;
  systemHeading: string;
  systemIntro: string;
  system: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  /**
   * Carries the semantic SEO weight of the page. Each heading renders as an H2.
   */
  deepDive?:
    | {
        heading: string;
        /**
         * Separate paragraphs with a blank line.
         */
        paragraphs: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as FAQPage structured data. Answer the question directly in the first sentence so AI answer engines can lift it cleanly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | Service)[] | null;
  cta: {
    heading: string;
    body: string;
  };
  /**
   * Controls the <title>, meta description and social preview for this page.
   */
  seo: {
    /**
     * Aim for 50-60 characters. Google truncates beyond roughly 60.
     */
    metaTitle: string;
    /**
     * Aim for 140-158 characters. Written to earn the click, not to describe.
     */
    metaDescription: string;
    /**
     * Optional. Falls back to the generated brand card if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles live at /growth-hub/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from title if left blank.
   */
  slug: string;
  publishedAt: string;
  category: number | Category;
  author: number | Author;
  /**
   * Surface this article on the homepage insights row.
   */
  featured?: boolean | null;
  title: string;
  /**
   * One or two sentences. Shown on cards and under the article title.
   */
  excerpt: string;
  /**
   * Optional. A generated gradient card is used when empty.
   */
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Rendered as FAQPage structured data. Answer the question directly in the first sentence so AI answer engines can lift it cleanly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as the conversion block at the end of the article.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Controls the <title>, meta description and social preview for this page.
   */
  seo: {
    /**
     * Aim for 50-60 characters. Google truncates beyond roughly 60.
     */
    metaTitle: string;
    /**
     * Aim for 140-158 characters. Written to earn the click, not to describe.
     */
    metaDescription: string;
    /**
     * Optional. Falls back to the generated brand card if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  /**
   * Calculated automatically on save.
   */
  readingMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from title if left blank.
   */
  slug: string;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Author entities. Published as Person structured data to support E-E-A-T signals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from name if left blank.
   */
  slug: string;
  name: string;
  role: string;
  bio: string;
  avatar?: (number | null) | Media;
  /**
   * Used for the sameAs property in Person schema. Strengthens entity resolution.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publish only verified results. Every number entered here should be traceable to an analytics export or a client sign-off.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * URL segment. Lowercase, hyphenated. Derived from title if left blank.
   */
  slug: string;
  order: number;
  /**
   * Show on the homepage featured work row.
   */
  featured?: boolean | null;
  title: string;
  /**
   * Confirm the client has approved being named.
   */
  client: string;
  /**
   * Links the case study into the industry hub.
   */
  industry?: (number | null) | Industry;
  services?: (number | Service)[] | null;
  summary: string;
  coverImage?: (number | null) | Media;
  /**
   * Optional link to the live site.
   */
  liveUrl?: string | null;
  /**
   * Separate paragraphs with a blank line.
   */
  challenge: string;
  strategy: string;
  execution: string;
  deliverables: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only publish figures you can evidence. Record the measurement window and source for each.
   */
  results?:
    | {
        /**
         * e.g. Organic sessions
         */
        metric: string;
        /**
         * e.g. +140%
         */
        value: string;
        /**
         * e.g. 6 months post-launch
         */
        period: string;
        /**
         * Where this number came from, e.g. GA4 export, Search Console.
         */
        source: string;
        id?: string | null;
      }[]
    | null;
  beforeAfter?: {
    beforeImage?: (number | null) | Media;
    afterImage?: (number | null) | Media;
    beforeNotes?: string | null;
    afterNotes?: string | null;
  };
  testimonial?: (number | null) | Testimonial;
  /**
   * Controls the <title>, meta description and social preview for this page.
   */
  seo: {
    /**
     * Aim for 50-60 characters. Google truncates beyond roughly 60.
     */
    metaTitle: string;
    /**
     * Aim for 140-158 characters. Written to earn the click, not to describe.
     */
    metaDescription: string;
    /**
     * Optional. Falls back to the generated brand card if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Publish real, attributed testimonials only. Anything unattributed reads as invented and costs more trust than it earns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role: string;
  company: string;
  avatar?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every qualified enquiry from the site. Scored on submission so the highest-value conversations surface first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'contacted' | 'call-booked' | 'proposal-sent' | 'won' | 'lost' | 'disqualified';
  /**
   * Calculated on submission from budget, timeline and brief quality.
   */
  score?: number | null;
  name: string;
  email: string;
  phone?: string | null;
  company: string;
  website?: string | null;
  /**
   * Free text as submitted, so the form stays usable for verticals we have not built a page for.
   */
  industry?: string | null;
  services?:
    | (
        | 'web-design'
        | 'web-development'
        | 'ecommerce'
        | 'seo'
        | 'local-seo'
        | 'google-ads'
        | 'meta-ads'
        | 'conversion-optimization'
        | 'ai-automation'
        | 'crm-systems'
        | 'branding'
        | 'website-maintenance'
        | 'full-system'
      )[]
    | null;
  budget?: ('under-5k' | '5k-15k' | '15k-35k' | '35k-75k' | '75k-plus' | 'unsure') | null;
  timeline?: ('urgent' | '1-3-months' | '3-6-months' | 'exploring') | null;
  message: string;
  /**
   * Page the form was submitted from.
   */
  sourcePath?: string | null;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  /**
   * Google click ID, for offline conversion import.
   */
  gclid?: string | null;
  notificationSent?: boolean | null;
  webhookDelivered?: boolean | null;
  /**
   * Populated automatically when a delivery attempt fails.
   */
  deliveryNotes?: string | null;
  /**
   * Not visible to the submitter.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'taxonomies';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  externalId?: T;
  slug?: T;
  status?: T;
  completeness?: T;
  name?: T;
  alternateNames?: T;
  usernamePrimary?: T;
  personTypes?: T;
  gender?: T;
  generation?: T;
  dateOfBirth?: T;
  nationality?: T;
  city?: T;
  countryCode?: T;
  countries?: T;
  regions?: T;
  industries?: T;
  sports?: T;
  platforms?: T;
  topics?: T;
  genres?: T;
  professions?: T;
  languages?: T;
  primaryIndustry?: T;
  sportRole?: T;
  niches?: T;
  audienceType?: T;
  audienceScope?: T;
  bioShort?: T;
  bioLong?: T;
  knownFor?: T;
  notableWork?: T;
  awards?: T;
  organizations?: T;
  brands?: T;
  profileImage?: T;
  coverImage?: T;
  socialProfiles?:
    | T
    | {
        platform?: T;
        handle?: T;
        url?: T;
        followers?: T;
        engagementRate?: T;
        lastCheckedAt?: T;
        id?: T;
      };
  websiteUrl?: T;
  wikipediaUrl?: T;
  officialSourceUrl?: T;
  verified?: T;
  verificationDate?: T;
  claimed?: T;
  editorialNotes?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies_select".
 */
export interface TaxonomiesSelect<T extends boolean = true> {
  type?: T;
  slug?: T;
  title?: T;
  description?: T;
  countryCode?: T;
  parent?: T;
  personCount?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  icon?: T;
  order?: T;
  category?: T;
  title?: T;
  navLabel?: T;
  tagline?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
      };
  intro?: T;
  problemsHeading?: T;
  problems?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  includedHeading?: T;
  includedIntro?: T;
  included?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  approachHeading?: T;
  approach?:
    | T
    | {
        step?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  outcomesHeading?: T;
  outcomesIntro?: T;
  outcomes?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  deepDive?:
    | T
    | {
        heading?: T;
        paragraphs?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  relatedIndustries?: T;
  cta?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  slug?: T;
  icon?: T;
  order?: T;
  title?: T;
  navLabel?: T;
  tagline?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
      };
  intro?: T;
  challengesHeading?: T;
  challengesIntro?: T;
  challenges?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  buyerBehaviourHeading?: T;
  buyerBehaviour?: T;
  systemHeading?: T;
  systemIntro?: T;
  system?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  deepDive?:
    | T
    | {
        heading?: T;
        paragraphs?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  cta?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  publishedAt?: T;
  category?: T;
  author?: T;
  featured?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  readingMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  featured?: T;
  title?: T;
  client?: T;
  industry?: T;
  services?: T;
  summary?: T;
  coverImage?: T;
  liveUrl?: T;
  challenge?: T;
  strategy?: T;
  execution?: T;
  deliverables?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  results?:
    | T
    | {
        metric?: T;
        value?: T;
        period?: T;
        source?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        beforeImage?: T;
        afterImage?: T;
        beforeNotes?: T;
        afterNotes?: T;
      };
  testimonial?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  score?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  website?: T;
  industry?: T;
  services?: T;
  budget?: T;
  timeline?: T;
  message?: T;
  sourcePath?: T;
  referrer?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  gclid?: T;
  notificationSent?: T;
  webhookDelivered?: T;
  deliveryNotes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Organization-level facts. These feed the footer, the contact page and the Organization structured data that search engines and AI answer engines read.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName: string;
  brandName: string;
  tagline: string;
  /**
   * The canonical one-paragraph definition of the company. Used in Organization schema and as the default meta description.
   */
  description: string;
  logo?: (number | null) | Media;
  /**
   * Leave empty unless accurate. Published in Organization schema.
   */
  foundingYear?: number | null;
  email: string;
  phone?: string | null;
  /**
   * Calendar link used by the "Book a Strategy Call" button. Leave empty to route that button to the contact page instead.
   */
  bookingUrl?: string | null;
  /**
   * Optional. Complete this before running Local SEO on your own brand, and keep it identical to your Google Business Profile.
   */
  address?: {
    streetAddress?: string | null;
    locality?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  serviceAreas?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform:
          | 'LinkedIn'
          | 'Instagram'
          | 'Facebook'
          | 'X'
          | 'YouTube'
          | 'GitHub'
          | 'Google Business Profile'
          | 'Clutch'
          | 'Other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Four at most. Every figure here should be defensible if a prospect asks you to back it up on a call.
   */
  trustStats?:
    | {
        /**
         * e.g. 150+
         */
        value: string;
        /**
         * e.g. Projects delivered
         */
        label: string;
        /**
         * lucide-react icon name in PascalCase.
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only add clients who have agreed to be named. Upload a logo, or leave it empty to render the name as a wordmark.
   */
  clients?:
    | {
        name: string;
        /**
         * Small line under the name, e.g. Law Firm.
         */
        descriptor?: string | null;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  brandName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  foundingYear?: T;
  email?: T;
  phone?: T;
  bookingUrl?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        locality?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  serviceAreas?:
    | T
    | {
        name?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  trustStats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        name?: T;
        descriptor?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  title: string;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableBlock".
 */
export interface DataTableBlock {
  /**
   * Optional. Rendered as the table caption and used by screen readers.
   */
  caption?: string | null;
  /**
   * One row per line, cells separated by a pipe character. The first line is the header row.
   */
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dataTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}